const { chromium } = require('playwright');
(async () => {
  const browser = await chromium.launch({ args: ['--no-sandbox'] });
  const page = await browser.newPage();
  page.on('console', (m) => { if (m.text().includes('[ref]')) console.log(m.text().slice(0, 110)); });
  await page.goto('http://localhost:5173/', { waitUntil: 'networkidle', timeout: 60000 });
  await page.waitForTimeout(2500);
  await page.locator('.tree .name', { hasText: '引用演示.md' }).click();
  await page.waitForTimeout(3000);
  await page.evaluate(() => document.querySelector('.milkdown .ProseMirror').focus());
  await page.keyboard.press('Control+End');
  await page.keyboard.press('Enter');
  console.log('--- 行首输入 @ ---');
  await page.keyboard.type('@');
  await page.waitForTimeout(500);
  console.log('菜单组数:', await page.locator('[data-ref-menu] .menu-group').count());
  await page.keyboard.press('Escape');
  await page.waitForTimeout(300);
  await page.keyboard.press('Enter');
  await page.keyboard.type(' @');
  await page.waitForTimeout(500);
  console.log('空格后输入 @ 菜单组数:', await page.locator('[data-ref-menu] .menu-group').count());
  await browser.close();
})();
