const { chromium } = require('playwright');
(async () => {
  const browser = await chromium.launch({ args: ['--no-sandbox'] });
  const page = await browser.newPage();
  await page.goto('http://localhost:5173/', { waitUntil: 'networkidle', timeout: 60000 });
  await page.waitForTimeout(2500);
  await page.locator('.tree .name', { hasText: 'Mermaid 图表集.md' }).click({ button: 'right' });
  await page.waitForTimeout(400);
  await page.locator('.menu-item.danger', { hasText: '删除' }).click();
  await page.waitForTimeout(400);
  const modalText = await page.locator('.modal').textContent();
  console.log('确认框内容:', modalText.slice(0, 80).replace(/\n/g, ' '));
  await page.locator('.modal .danger').click();
  await page.waitForTimeout(1500);
  const toasts = await page.locator('.toast').allTextContents();
  console.log('toasts:', JSON.stringify(toasts));
  const still = await page.locator('.tree .name', { hasText: 'Mermaid 图表集.md' }).count();
  console.log('树中仍在:', still > 0);
  await browser.close();
})();
