const { chromium } = require('playwright');
(async () => {
  const browser = await chromium.launch({ args: ['--no-sandbox'] });
  const page = await browser.newPage();
  page.on('pageerror', (e) => console.log('PAGEERROR:', e.message));
  await page.goto('http://localhost:5173/', { waitUntil: 'networkidle', timeout: 60000 });
  await page.waitForTimeout(2500);
  // 复刻 e2e 前 9 步
  await page.locator('.tree .node', { hasText: '笔记' }).first().click();
  await page.waitForTimeout(400);
  await page.locator('.tree .name', { hasText: '会议记录.md' }).click();
  await page.waitForTimeout(2500);
  await page.locator('.icon-col .icon-btn').first().click();
  await page.waitForTimeout(400);
  await page.keyboard.press('End');
  await page.keyboard.type(' 新布局测试');
  await page.waitForTimeout(600);
  await page.keyboard.press('Control+s');
  await page.waitForTimeout(800);
  await page.locator('.icon-col .icon-btn').nth(1).click();
  await page.waitForTimeout(500);
  await page.selectOption('.settings-modal select', 'nord-dark');
  await page.waitForTimeout(600);
  await page.locator('.tab-btn', { hasText: '快捷键' }).click();
  await page.waitForTimeout(300);
  await page.locator('.shortcut-row', { hasText: '打开设置' }).locator('.keybtn').click();
  await page.waitForTimeout(300);
  await page.keyboard.press('Alt+Shift+P');
  await page.waitForTimeout(300);
  await page.keyboard.press('Escape');
  await page.waitForTimeout(400);
  await page.keyboard.press('Alt+Shift+P');
  await page.waitForTimeout(500);
  await page.keyboard.press('Escape');
  await page.waitForTimeout(400);
  // 现在 Ctrl+B
  const focusedBefore = await page.evaluate(() => document.activeElement?.tagName + '.' + (document.activeElement?.className || ''));
  console.log('Ctrl+B 前焦点:', focusedBefore);
  const shortcuts = await page.evaluate(() => JSON.parse(localStorage.getItem('milkdown-note-settings-v1') || '{}').shortcuts);
  console.log('toggleSidebar 快捷键:', shortcuts.toggleSidebar, '| settings:', shortcuts.settings);
  await page.keyboard.press('Control+b');
  await page.waitForTimeout(400);
  const c1 = await page.locator('.content-col').evaluate(el => el.classList.contains('collapsed'));
  console.log('Ctrl+B 收纳结果:', c1);
  await browser.close();
})();
