const { chromium } = require('playwright');
(async () => {
  const browser = await chromium.launch({ args: ['--no-sandbox'] });
  const page = await browser.newPage();
  page.on('console', (m) => { if (m.text().includes('[ref]')) console.log(m.text().slice(0, 110)); });
  await page.goto('http://localhost:5173/', { waitUntil: 'networkidle', timeout: 60000 });
  await page.waitForTimeout(2500);
  await page.locator('.sidebar-actions .mini', { hasText: '＋文件' }).click();
  await page.waitForTimeout(300);
  await page.locator('.tree .rename-input').fill('过滤检查.md');
  await page.keyboard.press('Enter');
  await page.waitForTimeout(1500);
  await page.evaluate(() => document.querySelector('.milkdown .ProseMirror').focus());
  await page.keyboard.press('Control+End');
  await page.keyboard.press('Enter');
  await page.keyboard.type('[[会议');
  await page.waitForTimeout(600);
  const docText = await page.evaluate(() => document.querySelector('.milkdown .ProseMirror').textContent.slice(0, 20));
  const entries = await page.locator('[data-ref-menu] .menu-group li span').allTextContents();
  const h6 = await page.locator('[data-ref-menu] .menu-group h6').textContent();
  console.log('文档文本:', JSON.stringify(docText));
  console.log('菜单条目:', JSON.stringify(entries));
  console.log('h6:', h6);
  await browser.close();
})();
