const { chromium } = require('playwright');
(async () => {
  const browser = await chromium.launch({ args: ['--no-sandbox'] });
  const page = await browser.newPage();
  page.on('console', (m) => { if (m.text().includes('[ref]')) console.log(m.text().slice(0, 120)); });
  await page.goto('http://localhost:5173/', { waitUntil: 'networkidle', timeout: 60000 });
  await page.waitForTimeout(2500);
  await page.locator('.sidebar-actions .mini', { hasText: '＋文件' }).click();
  await page.waitForTimeout(300);
  await page.locator('.tree .rename-input').fill('流程日志.md');
  await page.keyboard.press('Enter');
  await page.waitForTimeout(1500);
  // 步骤1-3
  await page.evaluate(() => document.querySelector('.milkdown .ProseMirror').focus());
  await page.keyboard.press('Control+End');
  await page.keyboard.press('Enter');
  await page.keyboard.type('[[');
  await page.waitForTimeout(400);
  await page.keyboard.type('会议');
  await page.waitForTimeout(400);
  await page.keyboard.press('Enter');
  await page.waitForTimeout(500);
  console.log('--- 步骤4 ---');
  await page.evaluate(() => document.querySelector('.milkdown .ProseMirror').focus());
  await page.keyboard.press('Control+End');
  await page.keyboard.press('Enter');
  await page.waitForTimeout(200);
  console.log('输入 ! 前 caret 状态:');
  await page.keyboard.type('!');
  await page.waitForTimeout(150);
  await page.keyboard.type('[');
  await page.waitForTimeout(150);
  await page.keyboard.type('[');
  await page.waitForTimeout(300);
  await page.keyboard.type('待办');
  await page.waitForTimeout(600);
  console.log('菜单组数:', await page.locator('[data-ref-menu] .menu-group').count());
  const st = await page.evaluate(async () => (await import('/src/editor/ref/menu/index.ts')).refMenuState);
  console.log('state:', JSON.stringify({ visible: st.visible, mode: st.mode }));
  await browser.close();
})();
