const { chromium } = require('playwright');
(async () => {
  const browser = await chromium.launch({ args: ['--no-sandbox'] });
  const page = await browser.newPage();
  page.on('console', (m) => { const t = m.text(); if (t.includes('[M3]')) console.log('LOG:', t.slice(0, 140)); });
  await page.goto('http://localhost:5173/', { waitUntil: 'networkidle', timeout: 60000 });
  await page.waitForTimeout(2500);
  await page.locator('.tree .name', { hasText: '引用演示.md' }).click();
  await page.waitForTimeout(3500);
  await page.evaluate(() => document.querySelector('.milkdown .ProseMirror').focus());
  await page.keyboard.press('Control+End');
  await page.keyboard.press('Enter');
  await page.keyboard.type('[[Mermaid');
  await page.waitForTimeout(600);
  await page.keyboard.press('Enter');
  await page.waitForTimeout(800);
  const collapsed = await page.locator('.content-col').evaluate(el => el.classList.contains('collapsed'));
  if (collapsed) { await page.locator('.icon-col .icon-btn').first().click(); await page.waitForTimeout(400); }
  await page.locator('.tree .name', { hasText: 'Mermaid 图表集.md' }).click({ button: 'right' });
  await page.waitForTimeout(400);
  await page.locator('.menu-item.danger', { hasText: '删除' }).click();
  await page.waitForTimeout(400);
  await page.locator('.modal .danger').click();
  await page.waitForTimeout(1500);
  await page.locator('a.ref-file.ref-broken').first().click();
  await page.waitForTimeout(800);
  console.log('菜单打开:', await page.locator('[data-ref-menu] .menu-group li').count() > 0);
  const labels = await page.locator('[data-ref-menu] .menu-group li > span:nth-child(2)').allTextContents();
  console.log('根条目:', JSON.stringify(labels));
  const noteIdx = labels.findIndex(t => t === '笔记');
  for (let i = 0; i < noteIdx; i++) await page.keyboard.press('ArrowDown');
  await page.keyboard.press('Enter');
  await page.waitForTimeout(500);
  const labels2 = await page.locator('[data-ref-menu] .menu-group li > span:nth-child(2)').allTextContents();
  console.log('笔记内:', JSON.stringify(labels2));
  const todoIdx = labels2.findIndex(t => t.includes('待办清单'));
  for (let i = 0; i < todoIdx; i++) await page.keyboard.press('ArrowDown');
  await page.keyboard.press('Enter');
  await page.waitForTimeout(1000);
  const md = await page.evaluate(() => window.__editorGetMarkdown());
  console.log('替换后含待办清单:', md.includes('[[笔记/待办清单]]'), '| 仍含 Mermaid:', md.includes('Mermaid'));
  console.log('断链数:', await page.locator('a.ref-file.ref-broken').count());
  await browser.close();
})();
