const { chromium } = require('playwright');
(async () => {
  const browser = await chromium.launch({ args: ['--no-sandbox'] });
  const page = await browser.newPage();
  page.on('console', (m) => { if (m.text().includes('[ref]')) console.log(m.text().slice(0, 160)); });
  await page.goto('http://localhost:5173/', { waitUntil: 'networkidle', timeout: 60000 });
  await page.waitForTimeout(2500);
  await page.locator('.tree .name', { hasText: '引用演示.md' }).click();
  await page.waitForTimeout(3000);
  await page.evaluate(() => document.querySelector('.milkdown .ProseMirror').focus());
  console.log('--- 输入 / ---');
  await page.keyboard.type('/');
  await page.waitForTimeout(500);
  const crepeMenu = await page.locator('.milkdown-slash-menu[data-show="true"]').count();
  console.log('crepe / 菜单可见:', crepeMenu);
  await page.keyboard.press('Escape');
  await page.waitForTimeout(300);
  console.log('--- 输入 [[ ---');
  await page.keyboard.type('[[');
  await page.waitForTimeout(500);
  const refOpen = await page.locator('[data-ref-menu] .menu-group').count();
  console.log('ref 菜单组数:', refOpen);
  await browser.close();
})();
