// AUTO-GENERATED by scripts/sync-demo.mjs —— 不要手改；demo/ 变更后运行 npm run sync:demo（predev/prebuild 自动执行）
// demo 目录是唯一源，mock 浏览器演示数据与其同步。
export const DEMO_FILES: Record<string, string> = {
  '.template/xxljob/xxljob.md': `doctype: xxljob

# 任务名称

## 基本信息

| 属性 | 值 |
| --- | --- |
| 执行器 | executor-name |
| JobHandler | handlerName |
| 调度类型 | cron |
| cron 表达式 | 0 0 0 * * ? |
| 固定速度(秒) |  |
| 固定延迟(秒) |  |
| 路由策略 | 分片广播 |
| 阻塞处理策略 | 单机串行 |
| 调度过期策略 | 忽略 |
| 任务超时(秒) | 60 |
| 失败重试次数 | 3 |
| 负责人 | 姓名 |
| 报警邮箱 | ops@example.com |
| 调度状态 | 启动 |

## 任务职责

一句话说明该任务做什么、何时触发、失败如何处理。

## 业务规则

- 规则一
- 规则二

## 关联数据

- [[数据库/xxx/表结构#xxx]]

## 变更记录

| 日期 | 变更人 | 变更内容 |
| --- | --- | --- |
| YYYY-MM-DD | 姓名 | 新增 |
`,
  '.template/xxljob/xxljob.rules.ts': `// xxljob 校验规则：一个 md 文件 = 一个 xxljob 任务（mode=hint，不阻止保存）
// 校验：基本信息表 / 执行器 / JobHandler / 调度类型 / cron / 路由策略 / 阻塞策略 / 任务职责 / 变更记录
import type { Rule, ValidationContext } from '@milkdown-note/validate'

const SCHEDULE_TYPES = ['cron', '固定速度', '固定延迟']
const ROUTE_STRATEGIES = ['第一个', '最后一个', '轮询', '随机', '一致性HASH', '最不经常使用', '最近最久未使用', '故障转移', '忙碌转移', '分片广播']
const BLOCK_STRATEGIES = ['单机串行', '丢弃后续调度', '覆盖之前调度']
const STATUS = ['启动', '停止']

/** 从「## 基本信息」表按「属性」名取值（列名支持 属性/项 + 值） */
function basicInfo(ctx: ValidationContext, label: string): string | null {
  const t = ctx.findTableAfterHeading('## 基本信息')
  if (!t) return null
  const h = t.headerRow()
  if (!h) return null
  const cols = h.cells().map((c) => c.text())
  const cKey = cols.findIndex((c) => /属性|项/.test(c))
  const cVal = cols.findIndex((c) => /值/.test(c))
  if (cKey < 0 || cVal < 0) return null
  for (const row of t.dataRows()) {
    if (row.cell(cKey).text().trim() === label) {
      const v = row.cell(cVal).text().trim()
      return v || null
    }
  }
  return null
}

export const rules: Rule[] = [
  {
    id: 'basic-table',
    label: '基本信息表存在',
    run(ctx) {
      const t = ctx.findTableAfterHeading('## 基本信息')
      if (!t) ctx.violation('缺少「基本信息」表格', 'error')
    },
  },
  {
    id: 'basic-headers',
    label: '基本信息表头为「属性 | 值」',
    run(ctx) {
      const t = ctx.findTableAfterHeading('## 基本信息')
      if (!t) return
      const h = t.headerRow()
      if (!h) ctx.violation('基本信息表缺少表头行', 'error')
      else {
        const cols = h.cells().map((c) => c.text())
        if (!cols.some((c) => /属性|项/.test(c)) || !cols.some((c) => /值/.test(c)))
          ctx.violation('基本信息表头应包含「属性」和「值」列', 'error')
      }
    },
  },
  {
    id: 'executor-required',
    label: '执行器必填',
    run(ctx) {
      const v = basicInfo(ctx, '执行器')
      if (!v) ctx.violation('「执行器」未填写', 'error')
    },
  },
  {
    id: 'handler-format',
    label: 'JobHandler 必填且为标识符',
    run(ctx) {
      const v = basicInfo(ctx, 'JobHandler')
      if (!v) ctx.violation('「JobHandler」未填写', 'warning')
      else if (!/^[a-zA-Z][a-zA-Z0-9_]*$/.test(v)) ctx.violation(\`JobHandler「\${v}」应为字母开头标识符（如 notifyHandler）\`, 'warning')
    },
  },
  {
    id: 'schedule-type',
    label: '调度类型枚举',
    run(ctx) {
      const v = basicInfo(ctx, '调度类型')
      if (v && !SCHEDULE_TYPES.includes(v)) ctx.violation(\`调度类型「\${v}」应为 \${SCHEDULE_TYPES.join('/')}\`, 'warning')
    },
  },
  {
    id: 'cron-format',
    label: 'cron 表达式格式',
    run(ctx) {
      const cron = basicInfo(ctx, 'cron 表达式')
      if (!cron) return
      const fields = cron.trim().split(/\\s+/)
      if (fields.length < 6 || fields.length > 7) ctx.violation(\`cron「\${cron}」应为「秒 分 时 日 月 周」6-7 段\`, 'warning')
    },
  },
  {
    id: 'route-strategy',
    label: '路由策略枚举',
    run(ctx) {
      const v = basicInfo(ctx, '路由策略')
      if (v && !ROUTE_STRATEGIES.includes(v)) ctx.violation(\`路由策略「\${v}」不在枚举内（\${ROUTE_STRATEGIES.join('/')}）\`, 'warning')
    },
  },
  {
    id: 'block-strategy',
    label: '阻塞处理策略枚举',
    run(ctx) {
      const v = basicInfo(ctx, '阻塞处理策略')
      if (v && !BLOCK_STRATEGIES.includes(v)) ctx.violation(\`阻塞处理策略「\${v}」应为 \${BLOCK_STRATEGIES.join('/')}\`, 'warning')
    },
  },
  {
    id: 'status-enum',
    label: '调度状态枚举',
    run(ctx) {
      const v = basicInfo(ctx, '调度状态')
      if (v && !STATUS.includes(v)) ctx.violation(\`调度状态「\${v}」应为 启动/停止\`, 'warning')
    },
  },
  {
    id: 'duty-section',
    label: '任务职责章节存在',
    run(ctx) {
      if (!ctx.findHeading('## 任务职责')) ctx.violation('缺少「## 任务职责」章节', 'warning')
    },
  },
  {
    id: 'change-log',
    label: '变更记录存在',
    run(ctx) {
      const t = ctx.findTableAfterHeading('## 变更记录')
      if (!t) ctx.violation('缺少「变更记录」表格', 'warning')
    },
  },
]
`,
  '.template/xxljob/xxljob.suggest.ts': `// xxljob suggest：把「基本信息」表的属性（执行器/JobHandler/调度类型...）作为可引用对象。
// 用法：其他文档写「执行器：[[xxljob/notify-executor/下游机构通知#执行器]]」
//   resolve 出「值:notify-executor」
import type { SuggestContext, SuggestObject } from '@milkdown-note/suggest'

export function objectsFor(ctx: SuggestContext): SuggestObject[] {
  const rows = ctx.tableAfterHeading('## 基本信息')
  if (!rows || rows.length < 2) return []
  const header = rows[0]
  const cKey = header.findIndex((h) => /属性|项/.test(h))
  const cVal = header.findIndex((h) => /值/.test(h))
  if (cKey < 0 || cVal < 0) return []
  return rows
    .slice(1)
    .filter((r) => r[cKey]?.trim() && r[cVal]?.trim())
    .map((r) => {
      const name = r[cKey].trim()
      return {
        id: name,
        label: name,
        fragment: '基本信息',
        resolve(ctx2: SuggestContext): string | null {
          const rs = ctx2.tableAfterHeading('## 基本信息') ?? []
          const row = rs.find((x) => x[cKey]?.trim() === name)
          if (!row || !row[cVal]) return null
          return \`值:\${row[cVal]}\`
        },
      }
    })
}
`,
  '.template/后端接口/后端接口.md': `doctype:后端接口

# {{接口名}}（调用下游：{{下游系统}}）

> 本模板由「消金业务合作平台」定义。每个 .md 文件描述**一个外部接口**（本系统调用下游系统）。
> 调用下游的接口与本系统接口一样需**高风险评估**：是否关键接口、字段级高风险（金额/幂等/业务状态等）、幂等/防重、分页必须搭配排序、交易状态判断。

## 基本信息

| 项 | 值 | 备注 |
| --- | --- | :--- |
| 下游系统 | {{资金方-XX银行}} | 被调用的外部系统全称 |
| 方法 | {{GET/POST/PUT/DELETE}} | |
| 路径 | {{/api/loan/apply}} | 外部系统提供的路径 |
| 版本号 | {{v1.0.0}} | 格式 \`vX.Y.Z\` |
| 是否关键接口 | {{是/否}} | 满足任意 1 条即为「是」：①涉及资金交易 ②涉及短信发送 ③涉及监管报送或内部结算 ④包含高风险字段 |
| 该接口涉及的业务范围 | {{业务范围}} | 穷举所有涉及产品；不接受「标准化的所有产品」这类含糊描述 |
| 并发限制要求 | {{无要求 / TPS ≤ X}} | 下游系统对调用方的并发限制（默认为无要求） |
| 超时时间 | {{3s}} | 连接 / 读取超时 |
| 重试机制 | {{最多 3 次，指数退避}} | 仅幂等前提下允许重试 |
| 幂等规则 | {{[[数据库/loan/loan_apply#apply_no]]}} | 说明使用的幂等规则，引用下方高风险字段中的幂等字段 |
| 防止重复调用外部接口的机制 | {{[[数据库/...]]}} | 发送外部接口前更新交易记录状态（记录是否发送外部），并通过乐观锁避免重复调用 |
| 交易状态判断 | {{[[数据库/loan/loan_apply#status]]}} | 准则：明确失败才是失败，明确成功才是成功，其他应作为处理中 |

## 接口详情

字段说明：

| 字段 | 类型 | 长度 | 是否高风险字段 | 高风险字段类型 | 数据来源 | 说明 |
| --- | --- | --- | --- | --- | --- | --- |
| {{field}} | {{bigint}} | {{20}} | {{是/否}} | {{金额/本金/利息/罚息/总额/单位/精度/四舍五入/还款方式/期次/业务状态/响应结果判断/发送前状态更新/幂等/防重/征信}} | {{[[数据库/...]] 或 [[接口文档/...]]}} | {{字段用途}} |

> 高风险字段（「是否高风险字段=是」）必须填写「数据来源」：来自 XX 表的 XX 字段、或本系统 XX 接口的 XX 字段响应，使用 \`[[wikilink]]\` 引用。

请求示例：

\`\`\`json
{
  "{{field}}": 0
}
\`\`\`

响应示例：

\`\`\`json
{
  "{{code}}": 0,
  "{{msg}}": "success"
}
\`\`\`

## 变更记录

| 版本 | 日期 | 变更说明 |
| --- | --- | --- |
| v1.0.0 | {{2026-08-06}} | {{初版}} |
`,
  '.template/接口文档/接口文档.export.ts': `// 接口文档模板的导出定义（M10 导出机制）
// 导出「对外版本」：提供给其他系统人员联调查看，过滤内部信息：
//   - 基本信息表仅保留对外行（方法/路径/版本号/业务范围/会调用该系统），
//     删除内部评估行（是否关键接口/并发量/幂等规则/防重复机制/交易状态判断/外部接口引用）
//   - 字段说明表仅保留列（字段/类型/长度/说明），删除内部列（是否高风险字段/高风险字段类型/数据来源）
//   - 删除「变更记录」章节
// 请求示例 / 响应示例保留。
import type { ExportContext, ExportResult } from '@milkdown-note/export'

/** 默认导出格式（「自动」模式） */
export const format: 'pdf' | 'docx' | 'md' = 'pdf'

/** 默认导出文件名（不含扩展名） */
export const filename: string = '接口文档-对外'

/** 基本信息表中对外保留的项 */
const KEEP_BASIC = ['方法', '路径', '版本号', '该接口涉及的业务范围', '会调用该接口的系统']

/** 字段说明表对外保留的列 */
const KEEP_FIELD_COLS = ['字段', '类型', '长度', '说明']

// 编辑器序列化的表格为对齐填充格式（\`| 项   | 值   |\`），用正则匹配表头
const BASIC_HEAD = /^\\|\\s*项\\s*\\|\\s*值\\s*\\|\\s*备注/
const FIELD_HEAD = /^\\|\\s*字段\\s*\\|\\s*类型\\s*\\|\\s*长度/
const SEP_RE = /^\\|[\\s:\\-]+\\|/

/** 可选：自定义导出内容（对外版本过滤） */
export const build = (ctx: ExportContext): ExportResult | null => {
  const lines = ctx.content.split('\\n')
  const out: string[] = []
  let inBasic = false
  let inFieldTable = false
  let inChangeLog = false
  let keepIdx: number[] = []

  for (const raw of lines) {
    const t = raw.trim()

    // 变更记录章节：直接跳过（文档末节，之后所有行）
    if (/^## 变更记录/.test(t)) {
      inChangeLog = true
      continue
    }
    if (inChangeLog) continue

    // ---- 基本信息表：仅保留对外行，且只留「项 | 值」两列（去掉备注） ----
    if (BASIC_HEAD.test(t)) {
      inBasic = true
      out.push('| 项 | 值 |')
      continue
    }
    if (inBasic) {
      if (SEP_RE.test(t)) {
        out.push('| --- | --- |')
        continue
      }
      if (!t.startsWith('|')) {
        inBasic = false
      } else {
        const cells = t.split('|').slice(1, -1).map((c) => c.trim())
        const item = cells[0] ?? ''
        if (KEEP_BASIC.includes(item)) out.push(\`| \${cells[0]} | \${cells[1] ?? ''} |\`)
        continue
      }
    }

    // ---- 字段说明表：仅保留列（字段/类型/长度/说明） ----
    if (FIELD_HEAD.test(t)) {
      inFieldTable = true
      const header = t.split('|').slice(1, -1).map((c) => c.trim())
      keepIdx = header
        .map((h, i) => (KEEP_FIELD_COLS.includes(h) ? i : -1))
        .filter((i) => i >= 0)
      out.push(\`| \${keepIdx.map((i) => header[i]).join(' | ')} |\`)
      continue
    }
    if (inFieldTable) {
      if (SEP_RE.test(t)) {
        const sep = t.split('|').slice(1, -1)
        out.push(\`| \${keepIdx.map((i) => sep[i] ?? '---').join(' | ')} |\`)
        continue
      }
      if (!t.startsWith('|')) {
        inFieldTable = false
      } else {
        const cells = t.split('|').slice(1, -1).map((c) => c.trim())
        out.push(\`| \${keepIdx.map((i) => cells[i] ?? '').join(' | ')} |\`)
        continue
      }
    }

    out.push(raw)
  }
  return { content: out.join('\\n') }
}
`,
  '.template/接口文档/接口文档.md': `doctype:接口文档

# {{接口名称}}（本系统提供）

> 本模板由「消金业务合作平台」定义。每个 .md 文件描述**一个接口**。
> 字段名即对象引用 id（如 \`[[接口文档/助贷/助贷接口#amount]]\`），请用英文标识符或无空格中文，避免 \`#\` / 空格破坏引用语法。

## 基本信息

| 项 | 值 | 备注 |
| --- | --- | :--- |
| 方法 | {{GET/POST/PUT/DELETE/PATCH}} | |
| 路径 | {{/api/xxx}} | 以 \`/\` 开头 |
| 版本号 | {{v1.0.0}} | 格式 \`vX.Y.Z\` |
| 是否关键接口 | {{是/否}} | 满足任意 1 条即为「是」：①涉及资金交易 ②涉及短信发送（不含工作平台通知）③涉及监管报送或内部结算 ④包含高风险字段 |
| 该接口涉及的业务范围 | {{业务范围}} | 穷举所有涉及产品；不接受「标准化的所有产品」这类含糊描述 |
| 会调用该接口的系统 | {{系统全称}} | 会调用该接口的系统全称 |
| 预计接口并发量 | {{TPS 及评估依据}} | 说明预估并发量及评估依据 |
| 幂等规则 | {{[[数据库/loan/loan_apply#apply_no]]}} | 说明使用的幂等规则，引用下方高风险字段中的幂等字段 |
| 涉及调用外部接口 | {{[[后端接口/...]]}} | 罗列该接口涉及调用的所有外部接口 |
| 防止重复调用外部接口的机制 | {{[[数据库/...]]}} | 发送外部接口前更新交易记录状态（记录是否发送外部），并通过乐观锁避免重复调用 |
| 是否涉及分页，分页必须搭配排序 | {{[[数据库/...]]}} | 说明是否涉及分页查询及搭配的排序机制 |
| 交易状态判断 | {{[[数据库/loan/loan_apply#status]]}} | 准则：明确失败才是失败，明确成功才是成功，其他应作为处理中 |

## 接口详情

### {{子接口名}}

字段说明：

| 字段 | 类型 | 长度 | 是否高风险字段 | 高风险字段类型 | 数据来源 | 说明 |
| --- | --- | --- | --- | --- | --- | --- |
| {{field}} | {{bigint}} | {{20}} | {{是/否}} | {{金额/本金/利息/罚息/总额/单位/精度/四舍五入/还款方式/期次/业务状态/响应结果判断/发送前状态更新/幂等/防重/征信}} | {{[[数据库/...]] 或 [[后端接口/...]]}} | {{字段用途}} |

> 高风险字段（「是否高风险字段=是」）必须填写「数据来源」：来自 XX 表的 XX 字段、或 XX 系统 XX 接口的 XX 字段响应，使用 \`[[wikilink]]\` 引用。

请求示例：

\`\`\`json
{
  "{{field}}": 0
}
\`\`\`

响应示例：

\`\`\`json
{
  "code": 0,
  "msg": "success"
}
\`\`\`

## 变更记录

| 版本 | 日期 | 变更说明 |
| --- | --- | --- |
| v1.0.0 | {{2026-08-06}} | {{初版}} |
`,
  '.template/接口文档/接口文档.rules.ts': `// 接口文档校验规则（mode=hint，不阻止保存；违规写入 .validate/report.md）
// 规则 9「请求/响应示例字段一致性」依赖 ValidationContext.findCodeBlocks（M7 新增）
import type { ValidationContext, Rule } from '@milkdown-note/validate'

const METHODS = ['GET', 'POST', 'PUT', 'DELETE', 'PATCH']
const HIGH_RISK_TYPES = ['金额', '本金', '利息', '罚息', '总额', '单位', '精度', '四舍五入', '还款方式', '期次', '业务状态', '响应结果判断', '发送前状态更新', '幂等', '防重', '征信']
/** 通用响应包装字段（非业务字段；规则 9 跳过其「出现未声明」检查） */
const WRAPPER_FIELDS = new Set(['code', 'msg', 'message', 'data', 'success', 'requestId', 'traceId', 'timestamp'])

/** 递归收集 JSON 对象所有 key（含嵌套/数组） */
function collectKeys(obj: unknown, out: Set<string>): void {
  if (!obj || typeof obj !== 'object') return
  if (Array.isArray(obj)) {
    for (const v of obj) collectKeys(v, out)
    return
  }
  for (const [k, v] of Object.entries(obj as Record<string, unknown>)) {
    out.add(k)
    collectKeys(v, out)
  }
}

/** 基本信息表「项」列匹配 key 的「值」列文本 */
function basicInfo(ctx: ValidationContext, key: string): string | null {
  const t = ctx.findTableAfterHeading('## 基本信息')
  if (!t) return null
  for (const row of t.rows()) {
    if (row.cell(0).text().trim() === key) return row.cell(1).text().trim()
  }
  return null
}

export const mode = 'hint' as const
export const report = { enabled: true, path: '.validate/report.md' }

export const rules: Rule[] = [
  {
    id: 'sections-required',
    label: '必备章节齐全',
    run(ctx) {
      for (const h of ['## 基本信息', '## 接口详情', '## 变更记录']) {
        if (!ctx.findHeading(h)) ctx.violation(\`缺少必备章节「\${h}」\`, 'error')
      }
    },
  },
  {
    id: 'basic-info-table',
    label: '基本信息表存在',
    run(ctx) {
      const t = ctx.findTableAfterHeading('## 基本信息')
      if (!t) { ctx.violation('缺少「基本信息」表格', 'error'); return }
      const h = t.headerRow()
      if (!h || !/项/.test(h.cell(0).text()) || !/值/.test(h.cell(1).text())) {
        ctx.violation('基本信息表表头应为「项 | 值 | 备注」', 'error')
      }
    },
  },
  {
    id: 'method-valid',
    label: '方法合法',
    run(ctx) {
      const m = basicInfo(ctx, '方法')
      if (m && !METHODS.includes(m.toUpperCase())) {
        ctx.violation(\`方法「\${m}」不在合法集合 {\${METHODS.join(',')}}\`, 'warning')
      }
    },
  },
  {
    id: 'path-format',
    label: '路径格式',
    run(ctx) {
      const p = basicInfo(ctx, '路径')
      if (p && !p.startsWith('/')) ctx.violation(\`路径「\${p}」应以 / 开头\`, 'warning')
    },
  },
  {
    id: 'version-format',
    label: '版本号格式',
    run(ctx) {
      const v = basicInfo(ctx, '版本号')
      if (v && !/^v\\d+\\.\\d+\\.\\d+$/.test(v)) ctx.violation(\`版本号「\${v}」应为 vX.Y.Z\`, 'warning')
    },
  },
  {
    id: 'critical-enum',
    label: '是否关键接口枚举',
    run(ctx) {
      const c = basicInfo(ctx, '是否关键接口')
      if (c && c !== '是' && c !== '否') ctx.violation('「是否关键接口」应为 是/否', 'warning')
    },
  },
  {
    id: 'field-spec-table',
    label: '字段说明表存在',
    run(ctx) {
      const t = ctx.findTableAfterHeading('## 接口详情')
      if (!t) { ctx.violation('「接口详情」下缺少字段说明表', 'error'); return }
      const h = t.headerRow()
      if (!h) { ctx.violation('字段说明表缺少表头', 'error'); return }
      const cols = h.cells().map((c) => c.text())
      if (!cols.some((c) => /字段/.test(c))) ctx.violation('字段说明表缺少「字段」列', 'error')
      if (!cols.some((c) => /是否高风险/.test(c))) ctx.violation('字段说明表缺少「是否高风险字段」列', 'error')
    },
  },
  {
    id: 'high-risk-source',
    label: '高风险字段必填数据来源',
    run(ctx) {
      const t = ctx.findTableAfterHeading('## 接口详情')
      if (!t) return
      const h = t.headerRow()
      if (!h) return
      const cols = h.cells().map((c) => c.text())
      const cField = cols.findIndex((c) => /字段/.test(c))
      const cRisk = cols.findIndex((c) => /是否高风险/.test(c))
      const cSrc = cols.findIndex((c) => /数据来源/.test(c))
      if (cRisk < 0 || cSrc < 0) return
      for (const row of t.dataRows()) {
        if (row.cell(cRisk).text().trim() !== '是') continue
        const src = row.cell(cSrc).text().trim()
        const field = cField >= 0 ? row.cell(cField).text().trim() : ''
        if (!src || src === '<br />' || /^\\{\\{.*\\}\\}$/.test(src)) {
          ctx.violation(\`高风险字段「\${field}」未填写数据来源\`, 'warning')
        }
      }
    },
  },
  {
    id: 'req-resp-field-consistency',
    label: '请求/响应示例字段与字段说明一致',
    run(ctx) {
      const t = ctx.findTableAfterHeading('## 接口详情')
      if (!t) return
      const h = t.headerRow()
      if (!h) return
      const cols = h.cells().map((c) => c.text())
      const cField = cols.findIndex((c) => /字段/.test(c))
      if (cField < 0) return
      const declared = new Set<string>()
      for (const row of t.dataRows()) {
        const f = row.cell(cField).text().trim()
        if (f && !/^\\{\\{.*\\}\\}$/.test(f)) declared.add(f)
      }
      const blocks = ctx.findCodeBlocks(/^json$/i) ?? []
      const sample = new Set<string>()
      for (const b of blocks) {
        try { collectKeys(JSON.parse(b.content), sample) } catch { /* 非 JSON 跳过 */ }
      }
      if (sample.size === 0) return // 无可解析 JSON 示例则跳过
      for (const f of declared) {
        if (!sample.has(f)) ctx.violation(\`字段「\${f}」在字段说明中登记，但请求/响应示例中未出现\`, 'warning')
      }
      for (const f of sample) {
        // 通用响应包装字段（code/msg/data 等）非业务字段，跳过「出现未声明」
        if (WRAPPER_FIELDS.has(f)) continue
        if (!declared.has(f)) ctx.violation(\`字段「\${f}」在请求/响应示例中出现，但字段说明中未登记\`, 'warning')
      }
    },
  },
]
`,
  '.template/接口文档/接口文档.suggest.ts': `// 接口文档 suggest：动态对象生成器
// 从「接口详情」下字段说明表提取每个字段为可引用对象。
// 用法：在设计文档写「放款金额取自 [[接口文档/助贷/助贷接口#amount]]」
//   resolve 出「类型:bigint 高风险:是 来源:[[数据库/loan/表结构#amount]]」
import type { SuggestContext, SuggestObject } from '@milkdown-note/suggest'

export function objectsFor(ctx: SuggestContext): SuggestObject[] {
  const rows = ctx.tableAfterHeading('## 接口详情')
  if (!rows || rows.length < 2) return []
  const header = rows[0]
  const cField = header.findIndex((h) => /字段/.test(h))
  const cType = header.findIndex((h) => /^类型$/.test(h))
  const cRisk = header.findIndex((h) => /是否高风险/.test(h))
  const cSrc = header.findIndex((h) => /数据来源/.test(h))
  if (cField < 0) return []
  return rows
    .slice(1)
    .filter((r) => r[cField]?.trim() && !/^\\{\\{.*\\}\\}$/.test(r[cField].trim()))
    .map((r) => {
      const name = r[cField].trim()
      return {
        id: name,
        label: name,
        fragment: '接口详情',
        resolve(ctx: SuggestContext): string | null {
          const rs = ctx.tableAfterHeading('## 接口详情') ?? []
          const row = rs.find((x) => x[cField]?.trim() === name)
          if (!row) return null
          const parts = [
            cType >= 0 && row[cType] && \`类型:\${row[cType]}\`,
            cRisk >= 0 && row[cRisk] && \`高风险:\${row[cRisk]}\`,
            cSrc >= 0 && row[cSrc] && \`来源:\${row[cSrc]}\`,
          ].filter(Boolean)
          return parts.length ? parts.join(' ') : null
        },
      }
    })
}
`,
  '.template/数据库/数据库.md': `doctype:数据库

# {{loan_apply}} {{放款申请表}}

> 本模板由「消金业务合作平台」定义。**1 个 .md 文件 = 1 张表**（无表清单章节）。
> 字段名即对象引用 id（如 \`[[数据库/loan/loan_apply#amount]]\`），请用英文标识符（下划线风格），避免 \`#\` / 空格破坏引用语法。

## 基本信息

| 项 | 值 | 备注 |
| --- | --- | :--- |
| 表名 | {{loan_apply}} | 英文标识符 |
| 中文名 | {{放款申请表}} | |
| schema | {{loan}} | 所属 schema |
| 版本号 | {{v0.1.0}} | 格式 \`vX.Y.Z\` |

## 字段说明

| 字段 | 类型 | 约束 | 说明 |
| --- | --- | --- | --- |
| {{id}} | {{bigint}} | {{PK 自增}} | {{主键}} |

> 字段名请用英文标识符（如 \`apply_no\`），接口文档的数据来源列会以 \`[[数据库/{{schema}}/{{表名}}#{{字段名}}]]\` 引用。

## 索引

| 索引名 | 字段 | 类型 | 说明 |
| --- | --- | --- | --- |
| {{uk_apply_no}} | {{apply_no}} | {{唯一}} | {{幂等去重}} |

## 变更记录

| 日期 | 变更内容 |
| --- | --- |
| {{2026-08-06}} | {{初版}} |
`,
  '.template/数据库/数据库.rules.ts': `// 数据库表结构校验规则（mode=hint，不阻止保存；违规写入 .validate/report.md）
// 1 个 .md 文件 = 1 张表：基本信息（表名/中文名/schema/版本号）+ 字段说明表 + 索引 + 变更记录
import type { ValidationContext, Rule } from '@milkdown-note/validate'

function basicInfo(ctx: ValidationContext, key: string): string | null {
  const t = ctx.findTableAfterHeading('## 基本信息')
  if (!t) return null
  for (const row of t.dataRows()) {
    if (row.cell(0).text().trim() === key) return row.cell(1).text().trim()
  }
  return null
}

export const mode = 'hint' as const
export const report = { enabled: true, path: '.validate/report.md' }

export const rules: Rule[] = [
  {
    id: 'sections-required',
    label: '必备章节齐全',
    run(ctx) {
      for (const h of ['## 基本信息', '## 字段说明', '## 变更记录']) {
        if (!ctx.findHeading(h)) ctx.violation(\`缺少必备章节「\${h}」\`, 'error')
      }
    },
  },
  {
    id: 'basic-info-table',
    label: '基本信息表存在',
    run(ctx) {
      const t = ctx.findTableAfterHeading('## 基本信息')
      if (!t) { ctx.violation('缺少「基本信息」表格', 'error'); return }
      const h = t.headerRow()
      if (!h || !/项/.test(h.cell(0).text()) || !/值/.test(h.cell(1).text())) {
        ctx.violation('基本信息表表头应为「项 | 值 | 备注」', 'error')
      }
      for (const key of ['表名', '中文名', 'schema', '版本号']) {
        if (!basicInfo(ctx, key)) ctx.violation(\`基本信息缺少「\${key}」\`, 'warning')
      }
    },
  },
  {
    id: 'table-name-format',
    label: '表名格式',
    run(ctx) {
      const t = basicInfo(ctx, '表名')
      if (t && !/^[a-zA-Z_][a-zA-Z0-9_]*$/.test(t)) {
        ctx.violation(\`表名「\${t}」应为英文标识符（无空格/特殊字符）\`, 'warning')
      }
    },
  },
  {
    id: 'version-format',
    label: '版本号格式',
    run(ctx) {
      const v = basicInfo(ctx, '版本号')
      if (v && !/^v\\d+\\.\\d+\\.\\d+$/.test(v)) ctx.violation(\`版本号「\${v}」应为 vX.Y.Z\`, 'warning')
    },
  },
  {
    id: 'field-table',
    label: '字段说明表存在',
    run(ctx) {
      const t = ctx.findTableAfterHeading('## 字段说明')
      if (!t) { ctx.violation('「字段说明」下缺少字段表', 'error'); return }
      if (t.dataRows().length === 0) { ctx.violation('字段说明表为空', 'error'); return }
      const h = t.headerRow()
      if (!h) { ctx.violation('字段说明表缺少表头', 'error'); return }
      const cols = h.cells().map((c) => c.text())
      if (!cols.some((c) => /字段/.test(c))) ctx.violation('字段说明表缺少「字段」列', 'error')
      if (!cols.some((c) => /^类型$/.test(c))) ctx.violation('字段说明表缺少「类型」列', 'error')
      if (!cols.some((c) => /约束/.test(c))) ctx.violation('字段说明表缺少「约束」列', 'warning')
      if (!cols.some((c) => /^说明$/.test(c))) ctx.violation('字段说明表缺少「说明」列', 'warning')
    },
  },
  {
    id: 'field-name-format',
    label: '字段名格式',
    run(ctx) {
      const t = ctx.findTableAfterHeading('## 字段说明')
      if (!t) return
      const h = t.headerRow()
      if (!h) return
      const cols = h.cells().map((c) => c.text())
      const cField = cols.findIndex((c) => /字段/.test(c))
      if (cField < 0) return
      for (const row of t.dataRows()) {
        const f = row.cell(cField).text().trim()
        if (!f || /^\\{\\{.*\\}\\}$/.test(f)) continue
        // 英文标识符或中文（无空格）；禁止空格/特殊字符（会破坏 wikilink 引用语法）
        if (!/^[a-zA-Z_][a-zA-Z0-9_]*$/.test(f) && !/^[\\u4e00-\\u9fa5]+$/.test(f)) {
          ctx.violation(\`字段「\${f}」应为英文标识符或无空格中文（当前含空格/特殊字符，无法被 wikilink 引用）\`, 'warning')
        }
      }
    },
  },
  {
    id: 'pk-exists',
    label: '主键',
    run(ctx) {
      const t = ctx.findTableAfterHeading('## 字段说明')
      if (!t) return
      const h = t.headerRow()
      if (!h) return
      const cols = h.cells().map((c) => c.text())
      const cCons = cols.findIndex((c) => /约束/.test(c))
      if (cCons < 0) return
      if (!t.dataRows().some((r) => /PK/i.test(r.cell(cCons).text()))) {
        ctx.violation('字段表缺少主键（约束列应含 PK）', 'warning')
      }
    },
  },
  {
    id: 'change-log',
    label: '变更记录非空',
    run(ctx) {
      const t = ctx.findTableAfterHeading('## 变更记录')
      if (!t) { ctx.violation('缺少「变更记录」表格', 'warning'); return }
      if (t.dataRows().length === 0) ctx.violation('变更记录为空', 'warning')
    },
  },
]
`,
  '.template/数据库/数据库.suggest.ts': `// 数据库表结构 suggest：动态对象生成器
// 1 个 .md 文件 = 1 张表：直接从「字段说明」表提取字段为可引用对象。
// 用法：在接口文档「数据来源」列写「[[数据库/loan/loan_apply#amount]]」
//   resolve 出「类型:decimal(18,2) 约束:非空 说明:放款金额（元）」
import type { SuggestContext, SuggestObject } from '@milkdown-note/suggest'

export function objectsFor(ctx: SuggestContext): SuggestObject[] {
  const rows = ctx.tableAfterHeading('## 字段说明')
  if (!rows || rows.length < 2) return []
  const h = rows[0]
  const cField = h.findIndex((x) => /字段/.test(x))
  const cType = h.findIndex((x) => /^类型$/.test(x))
  const cCons = h.findIndex((x) => /约束/.test(x))
  const cDesc = h.findIndex((x) => /^说明$/.test(x))
  if (cField < 0) return []
  // 表名（基本信息表「表名」行）作 fragment，便于定位
  const bi = ctx.tableAfterHeading('## 基本信息') ?? []
  const tRow = bi.slice(1).find((r) => r[0]?.trim() === '表名')
  const tableName = tRow?.[1]?.trim() ?? ''
  return rows
    .slice(1)
    .filter((r) => r[cField]?.trim() && !/^\\{\\{.*\\}\\}$/.test(r[cField].trim()))
    .map((r) => {
      const name = r[cField].trim()
      const type = cType >= 0 ? (r[cType] ?? '') : ''
      const cons = cCons >= 0 ? (r[cCons] ?? '') : ''
      const desc = cDesc >= 0 ? (r[cDesc] ?? '') : ''
      return {
        id: name,
        label: name,
        fragment: tableName || '字段说明',
        resolve(): string | null {
          const parts = [type && \`类型:\${type}\`, cons && \`约束:\${cons}\`, desc && \`说明:\${desc}\`].filter(Boolean)
          return parts.length ? parts.join(' ') : null
        },
      }
    })
}
`,
  '.validate/report.md': `# 校验报告

- 文件：接口文档/助贷/助贷接口-违规.md
- 模板：接口文档
- 模式：hint
- 时间：2026/8/17 16:54:08
- 违规：6（error 0 / warning 6）

## 违规列表

- [warning] 路径「api/loan/apply」应以 / 开头（规则：路径格式）
- [warning] 版本号「1.0」应为 vX.Y.Z（规则：版本号格式）
- [warning] 「是否关键接口」应为 是/否（规则：是否关键接口枚举）
- [warning] 高风险字段「amount」未填写数据来源（规则：高风险字段必填数据来源）
- [warning] 字段「status」在字段说明中登记，但请求/响应示例中未出现（规则：请求/响应示例字段与字段说明一致）
- [warning] 字段「extraField」在请求/响应示例中出现，但字段说明中未登记（规则：请求/响应示例字段与字段说明一致）`,
  'README.md': `# 消金业务合作平台111

一套业务管理系统：接收上游发送的意向贷款客户，经**路由**输出到不同下游机构，完成**助贷、增信**等业务，合作完成贷款发放。核心业务模块：路由、进件、助贷、增信。

## 目录约定

| 目录            | 含义                    | 组织方式                    |
| ------------- | --------------------- | ----------------------- |
| \`20260806/\` 等 | 迭代窗口（批次），需求/设计文档按窗口归档 | 窗口 → 项目                 |
| \`流程图/\`        | 系统当前最新状态 · 流程图        | 按功能模块                   |
| \`接口文档/\`       | 本系统提供的接口服务            | 按功能模块                   |
| \`后端接口/\`       | 调用下游系统的接口             | 按下游系统                   |
| \`数据库/\`        | 表结构 + 数据维护            | 按 schema / 数据维护按日期      |
| \`xxljob/\`     | 批任务管理                 | 按执行器                    |
| \`配置/\`         | 运行配置                  | 按类型（nginx / apollo）→ 应用 |
| \`.template/\`  | 模板域（待逐个确认）            | 每模板一个目录                 |

> 说明：流程图 / 接口文档 / 后端接口 / 数据库 / xxljob / 配置 保存的是**系统功能描述的当前最新状态**（活文档，跨窗口持续更新）；迭代窗口目录保存各迭代的需求与设计快照。

> 当前全部文件为**简单示例**，待逐文件确认模板与校验规则后完善。
>
> <br />

![[流程图/助贷/助贷放款流程]]

# 引用示例2

![[验收场景/git-diff/08-嵌入引用与摘要]]

`,
  'probe.md': `# A

## B

| 1  | 6                                                  | 1      |
| :- | :------------------------------------------------- | :----- |
| 2  | 1111111111111111111111111111111111111111111111111  | 222233 |
| 2  | 5111                                               | 222233 |
| 2  | 5111                                               | 222233 |
| 2  | 11111111111111111111111111111111111111111111111111 | 222233 |
| 2  | 5111                                               | 222233 |
| 2  | 5111                                               | 222233 |

`,
  'xxljob/notify-executor/下游机构通知-违规.md': `doctype: xxljob

# 下游机构通知（违规示例）

## 基本信息

| 属性 | 值 |
| --- | --- |
| 执行器 |  |
| JobHandler | 下游通知 handler |
| 调度类型 | 每分钟 |
| cron 表达式 | 0/30 * * * ? |
| 固定速度(秒) |  |
| 固定延迟(秒) |  |
| 路由策略 | 广播 |
| 阻塞处理策略 | 跳过 |
| 调度过期策略 | 忽略 |
| 任务超时(秒) | 60 |
| 失败重试次数 | 3 |
| 负责人 | 李四 |
| 报警邮箱 | ops@xiang.com |
| 调度状态 | 运行中 |

## 业务规则

- 分片：按 customer_id 取模分片。

## 变更记录

| 日期 | 变更人 | 变更内容 |
| --- | --- | --- |
| 2026-08-07 | 李四 | 新增 |
`,
  'xxljob/notify-executor/下游机构通知.md': `doctype: xxljob

# 下游机构通知

## 基本信息

| 属性 | 值 |
| --- | --- |
| 执行器 | notify-executor |
| JobHandler | notifyDownstreamHandler |
| 调度类型 | cron |
| cron 表达式 | 0 0/30 * * * ? |
| 固定速度(秒) |  |
| 固定延迟(秒) |  |
| 路由策略 | 分片广播 |
| 阻塞处理策略 | 单机串行 |
| 调度过期策略 | 忽略 |
| 任务超时(秒) | 60 |
| 失败重试次数 | 3 |
| 负责人 | 李四 |
| 报警邮箱 | ops@xiang.com |
| 调度状态 | 启动 |

## 任务职责

放款/还款结果落库后，每 30 分钟分片扫描待通知记录，调用下游助贷机构结果回传接口；失败重试 3 次仍失败则写入失败队列并告警。

## 业务规则

- 幂等：以 [[接口文档/助贷/助贷接口#applyNo]] 为幂等键，同一放款申请重复通知不产生重复扣款。
- 分片：按 customer_id 取模分片，各执行器实例只处理本分片。
- 失败：超过重试次数的记录进入人工补偿通道。

## 关联数据

- [[数据库/loan/表结构#apply_no]]
- [[数据库/loan/表结构#status]]

## 变更记录

| 日期 | 变更人 | 变更内容 |
| --- | --- | --- |
| 2026-08-07 | 李四 | 新增 |
`,
  'xxljob/notify-executor/还款结果通知.md': `doctype: xxljob

# 还款结果通知

## 基本信息

| 属性 | 值 |
| --- | --- |
| 执行器 | notify-executor |
| JobHandler | repayResultNotifyHandler |
| 调度类型 | cron |
| cron 表达式 | 0 */5 * * * ? |
| 固定速度(秒) |  |
| 固定延迟(秒) |  |
| 路由策略 | 轮询 |
| 阻塞处理策略 | 丢弃后续调度 |
| 调度过期策略 | 忽略 |
| 任务超时(秒) | 30 |
| 失败重试次数 | 2 |
| 负责人 | 王五 |
| 报警邮箱 | ops@xiang.com |
| 调度状态 | 启动 |

## 任务职责

每 5 分钟轮询还款流水表，将已结清/逾期还款结果通知助贷机构，避免账务延迟。

## 业务规则

- 通知幂等：以 repay_no 唯一约束防重，重复调度不重复通知。
- 阻塞处理：任务未跑完时丢弃后续调度，防止通知堆积。

## 关联数据

- [[数据库/loan/表结构#repay_no]]

## 变更记录

| 日期 | 变更人 | 变更内容 |
| --- | --- | --- |
| 2026-08-07 | 王五 | 新增 |
`,
  'xxljob/route-executor/路由批量匹配.md': `doctype: xxljob

# 路由批量匹配

## 基本信息

| 属性 | 值 |
| --- | --- |
| 执行器 | route-executor |
| JobHandler | routeBatchMatchHandler |
| 调度类型 | cron |
| cron 表达式 | 0 0 2 * * ? |
| 固定速度(秒) |  |
| 固定延迟(秒) |  |
| 路由策略 | 分片广播 |
| 阻塞处理策略 | 单机串行 |
| 调度过期策略 | 立即执行一次 |
| 任务超时(秒) | 300 |
| 失败重试次数 | 3 |
| 负责人 | 赵六 |
| 报警邮箱 | ops@xiang.com |
| 调度状态 | 启动 |

## 任务职责

每日 02:00 对当日新进件批量执行客户路由匹配（征信校验 → 机构打分 → 路由决策），结果写路由结果表，供放款环节读取。

## 业务规则

- 前置：进件必须完成 [[接口文档/进件/进件接口#applyNo]] 进件登记且状态为待路由。
- 路由决策：命中机构白名单规则直接路由，未命中进入人工复核。
- 结果落库：匹配结果写 [[数据库/route/表结构#route_result]]，失败重试至多 3 次。

## 关联数据

- [[数据库/route/表结构#route_result]]

## 变更记录

| 日期 | 变更人 | 变更内容 |
| --- | --- | --- |
| 2026-08-07 | 赵六 | 新增 |
`,
  'xxljob/route-executor/路由规则缓存刷新.md': `doctype: xxljob

# 路由规则缓存刷新

## 基本信息

| 属性 | 值 |
| --- | --- |
| 执行器 | route-executor |
| JobHandler | routeRuleRefreshHandler |
| 调度类型 | 固定速度 |
| cron 表达式 |  |
| 固定速度(秒) | 600 |
| 固定延迟(秒) |  |
| 路由策略 | 第一个 |
| 阻塞处理策略 | 覆盖之前调度 |
| 调度过期策略 | 忽略 |
| 任务超时(秒) | 60 |
| 失败重试次数 | 1 |
| 负责人 | 赵六 |
| 报警邮箱 | ops@xiang.com |
| 调度状态 | 启动 |

## 任务职责

每 10 分钟从 Apollo 拉取最新路由规则并刷新本地缓存，使路由规则变更在 10 分钟内生效。

## 业务规则

- 版本比对：本地缓存版本与 Apollo 配置版本一致时跳过刷新。
- 失败兜底：刷新失败保留旧缓存并告警，不阻断在线路由。

## 关联数据

- [[数据库/route/表结构#rule_version]]

## 变更记录

| 日期 | 变更人 | 变更内容 |
| --- | --- | --- |
| 2026-08-07 | 赵六 | 新增 |
`,
  '后端接口/助贷机构-XX助贷/助贷接口/助贷放款申请接口.md': `doctype:后端接口

# 助贷放款申请接口

## 基本信息

| 项 | 值 | 备注 |
| --- | --- | :--- |
| 方法 | POST | |
| 路径 | /loan/apply | |
| 版本号 | v1.0.0 | |
| 是否关键接口 | 是 | 涉及资金交易；包含高风险字段（金额/期次/还款方式/业务状态） |
| 该接口涉及的业务范围 | 助贷放款：合作机构A放款、合作机构B放款 | 穷举所有涉及产品 |
| 接口提供方 | 助贷机构-XX助贷 | |
| 并发限制要求 | TPS ≤ 5 | 2026-08-14 商务XXX与外部约定 |
| 幂等规则 | [[#applyNo]] | 以申请号 applyNo 作幂等键，重复请求返回原结果。0806与商务XX确认，由资金方-XX银行确保唯一性。 |
| 涉及调用外部接口 | [[后端接口/资金方-XX银行/放款接口]] | 申请受理后调资金方放款接口 |
| 防止重复调用外部接口的机制 | [[数据库/loan/loan_apply#status]] | 发送外部前更新 loan.status=SENDING（乐观锁），防止重复发起放款 |
| 交易状态判断 | [[#status]] | 明确成功=SUCCESS、明确失败=FAIL，其余=PROCESSING 视为处理中 |

## 接口详情

### 助贷放款申请

字段说明：

| 字段 | 类型 | 长度 | 是否高风险字段 | 高风险字段类型 | 数据来源 | 说明 |
| --- | --- | --- | --- | --- | --- | --- |
| applyNo | string | 32 | 是 | 幂等 | [[数据库/loan/loan_apply#apply_no]] | 放款申请号，幂等键 |
| customerId | bigint | 20 | 否 |  | [[数据库/customer/customer_info#id]] | 客户ID |
| amount | bigint | 20 | 是 | 金额 | [[数据库/loan/loan_apply#amount]] | 放款金额（单位：分） |
| term | int | 4 | 是 | 期次 | [[数据库/loan/loan_apply#term]] | 期数 |
| repaymentMethod | string | 16 | 是 | 还款方式 | [[数据库/loan/loan_apply#repayment_method]] | 还款方式（等额本息/等额本金/先息后本） |
| applyDate | date | 10 | 否 |  | [[数据库/loan/loan_apply#apply_date]] | 申请日期 |
| status | string | 16 | 是 | 业务状态 | [[数据库/loan/loan_apply#status]] | 交易状态：PROCESSING/SUCCESS/FAIL |

请求示例：

\`\`\`json
{
  "applyNo": "APL20260806001",
  "customerId": 100200300,
  "amount": 5000000,
  "term": 12,
  "repaymentMethod": "EQUAL_INSTALLMENT",
  "applyDate": "2026-08-06"
}
\`\`\`

响应示例：

\`\`\`json
{
  "code": 0,
  "msg": "success",
  "data": {
    "applyNo": "APL20260806001",
    "status": "PROCESSING"
  }
}
\`\`\`

## 变更记录

| 版本 | 日期 | 变更说明 |
| --- | --- | --- |
| v1.0.0 | 2026-08-06 | 初版 |
`,
  '后端接口/助贷机构-XX助贷/助贷接口/进件推送接口.md': `doctype:后端接口

# 进件推送接口（调用下游：助贷机构-XX助贷）

## 基本信息

| 项 | 值 | 备注 |
| --- | --- | :--- |
| 下游系统 | 助贷机构-XX助贷 | 被调用的外部系统全称 |
| 方法 | POST | |
| 路径 | /api/entry/push | 外部系统提供的路径 |
| 版本号 | v1.0.0 | |
| 是否关键接口 | 是 | 包含高风险字段（金额/期次/还款方式/业务状态/幂等） |
| 该接口涉及的业务范围 | 助贷进件 | |
| 并发限制要求 | TPS ≤ 5 | 2026-08-14 商务与助贷机构约定 |
| 超时时间 | 3s | |
| 重试机制 | 最多 3 次，指数退避 | 幂等键进件号去重 |
| 幂等规则 | [[#entryNo]] | 进件号作幂等键，重复推送返回原结果 |
| 防止重复调用外部接口的机制 | [[数据库/loan/loan_apply#status]] | 发送前更新记录状态（乐观锁），防止重复推送 |
| 交易状态判断 | [[#status]] | 明确成功=SUCCESS、明确失败=FAIL，其余=PROCESSING 视为处理中 |

## 接口详情

字段说明：

| 字段 | 类型 | 长度 | 是否高风险字段 | 高风险字段类型 | 数据来源 | 说明 |
| --- | --- | --- | --- | --- | --- | --- |
| entryNo | string | 32 | 是 | 幂等 | [[数据库/loan/loan_apply#apply_no]] | 进件号，幂等键 |
| customerId | bigint | 20 | 否 |  | [[数据库/customer/customer_info#id]] | 客户ID |
| amount | bigint | 20 | 是 | 金额 | [[数据库/loan/loan_apply#amount]] | 贷款金额（单位：分） |
| term | int | 4 | 是 | 期次 | [[数据库/loan/loan_apply#term]] | 期数 |
| repaymentMethod | string | 16 | 是 | 还款方式 | [[数据库/loan/loan_apply#repayment_method]] | 还款方式（等额本息/等额本金/先息后本） |
| status | string | 16 | 是 | 业务状态 | [[数据库/loan/loan_apply#status]] | 进件状态：PROCESSING/SUCCESS/FAIL |

请求示例：

\`\`\`json
{
  "entryNo": "ENT20260806001",
  "customerId": 100200300,
  "amount": 5000000,
  "term": 12,
  "repaymentMethod": "EQUAL_INSTALLMENT"
}
\`\`\`

响应示例：

\`\`\`json
{
  "code": 0,
  "msg": "success",
  "data": {
    "entryNo": "ENT20260806001",
    "status": "PROCESSING"
  }
}
\`\`\`

## 变更记录

| 版本 | 日期 | 变更说明 |
| --- | --- | --- |
| v1.0.0 | 2026-08-06 | 初版 |
`,
  '后端接口/增信机构-XX担保/增信接口.md': `doctype:后端接口

# 增信申请接口（调用下游：增信机构-XX担保）

## 基本信息

| 项 | 值 | 备注 |
| --- | --- | :--- |
| 下游系统 | 增信机构-XX担保 | 被调用的外部系统全称 |
| 方法 | POST | |
| 路径 | /api/credit/apply | 外部系统提供的路径 |
| 版本号 | v1.0.0 | |
| 是否关键接口 | 是 | 涉及征信与资金交易；包含高风险字段（金额/业务状态/幂等） |
| 该接口涉及的业务范围 | 助贷增信 | |
| 并发限制要求 | TPS ≤ 3 | 与担保机构约定 |
| 超时时间 | 3s | |
| 重试机制 | 最多 3 次，指数退避 | 幂等键增信申请号去重 |
| 幂等规则 | [[#creditNo]] | 增信申请号作幂等键，重复请求返回原结果 |
| 防止重复调用外部接口的机制 | [[数据库/loan/loan_apply#status]] | 发送前更新记录状态（乐观锁），防止重复发起增信 |
| 交易状态判断 | [[#status]] | 明确成功=SUCCESS、明确失败=FAIL，其余=PROCESSING 视为处理中 |

## 接口详情

字段说明：

| 字段 | 类型 | 长度 | 是否高风险字段 | 高风险字段类型 | 数据来源 | 说明 |
| --- | --- | --- | --- | --- | --- | --- |
| creditNo | string | 32 | 是 | 幂等 | [[数据库/loan/loan_apply#apply_no]] | 增信申请号，幂等键（关联放款申请号） |
| customerId | bigint | 20 | 否 |  | [[数据库/customer/customer_info#id]] | 客户ID |
| guaranteeAmount | bigint | 20 | 是 | 金额 | [[数据库/loan/loan_apply#amount]] | 担保金额（单位：分） |
| status | string | 16 | 是 | 业务状态 | [[数据库/loan/loan_apply#status]] | 增信状态：PROCESSING/SUCCESS/FAIL |

请求示例：

\`\`\`json
{
  "creditNo": "CRD20260806001",
  "customerId": 100200300,
  "guaranteeAmount": 5000000
}
\`\`\`

响应示例：

\`\`\`json
{
  "code": 0,
  "msg": "success",
  "data": {
    "creditNo": "CRD20260806001",
    "status": "PROCESSING"
  }
}
\`\`\`

## 变更记录

| 版本 | 日期 | 变更说明 |
| --- | --- | --- |
| v1.0.0 | 2026-08-06 | 初版 |
`,
  '后端接口/资金方-XX银行/放款接口.md': `doctype:后端接口

# 放款申请接口（调用下游：资金方-XX银行）

## 基本信息

| 项 | 值 | 备注 |
| --- | --- | :--- |
| 下游系统 | 资金方-XX银行 | 被调用的外部系统全称 |
| 方法 | POST | |
| 路径 | /api/loan/apply | 外部系统提供的路径 |
| 版本号 | v1.0.0 | |
| 是否关键接口 | 是 | 涉及资金交易；包含高风险字段（金额/业务状态/幂等） |
| 该接口涉及的业务范围 | 助贷放款 | |
| 并发限制要求 | 无要求 | 与银行约定按需申请，无固定限制 |
| 超时时间 | 3s | |
| 重试机制 | 最多 3 次，指数退避 | 幂等键放款申请号去重 |
| 幂等规则 | [[#loanApplyNo]] | 放款申请号作幂等键，重复请求返回原结果 |
| 防止重复调用外部接口的机制 | [[数据库/loan/loan_apply#status]] | 发送前更新 loan.status=SENDING（乐观锁），防止重复放款 |
| 交易状态判断 | [[#status]] | 明确成功=SUCCESS、明确失败=FAIL，其余=PROCESSING 视为处理中 |

## 接口详情

字段说明：

| 字段 | 类型 | 长度 | 是否高风险字段 | 高风险字段类型 | 数据来源 | 说明 |
| --- | --- | --- | --- | --- | --- | --- |
| loanApplyNo | string | 32 | 是 | 幂等 | [[数据库/loan/loan_apply#apply_no]] | 放款申请号，幂等键 |
| customerId | bigint | 20 | 否 |  | [[数据库/customer/customer_info#id]] | 客户ID |
| amount | bigint | 20 | 是 | 金额 | [[数据库/loan/loan_apply#amount]] | 放款金额（单位：分） |
| status | string | 16 | 是 | 业务状态 | [[数据库/loan/loan_apply#status]] | 放款状态：PROCESSING/SUCCESS/FAIL |

请求示例：

\`\`\`json
{
  "loanApplyNo": "APL20260806001",
  "customerId": 100200300,
  "amount": 5000000
}
\`\`\`

响应示例：

\`\`\`json
{
  "code": 0,
  "msg": "success",
  "data": {
    "loanApplyNo": "APL20260806001",
    "status": "PROCESSING"
  }
}
\`\`\`

## 变更记录

| 版本 | 日期 | 变更说明 |
| --- | --- | --- |
| v1.0.0 | 2026-08-06 | 初版 |
`,
  '宽标题演示.md': `# 这是一个用于演示自适应宽度的非常非常非常非常长的标题文字样例

## 章节甲

正文

| 1<nbr />2<nbr />3 | 2                                                                         | 2                                             |
| :---------------- | :------------------------------------------------------------------------ | :-------------------------------------------- |
| 6                 | 5                                                                         | 43                                            |
| 67788             | 111111111111111<nbr />111111111111111111111111111111111111111111111111111 | 241111111111111111111111111111111<nbr />12314 |

<br />

![[验收场景/git-diff/08-嵌入引用与摘要]]

`,
  '布局探测.md': `# 平台指南

## 章节 01

正文 1。

## 章节 02

正文 2。

## 章节 03

正文 3。

## 章节 04

正文 4。

## 章节 05

正文 5。

## 章节 06

正文 6。

## 章节 07

正文 7。

## 章节 08

正文 8。

## 章节 09

正文 9。

## 章节 10

正文 10。

## 章节 11

正文 11。

## 章节 12

正文 12。

## 章节 13

正文 13。

## 章节 14

正文 14。

## 章节 15

正文 15。

## 章节 16

正文 16。

## 章节 17

正文 17。

## 章节 18

正文 18。

## 章节 19

正文 19。

## 章节 20

正文 20。

`,
  '布局测试.md': `# 平台指南

## 章节 01

第 1 章正文，多行内容。

- 要点一
- 要点二
- 要点三

## 章节 02

第 2 章正文，多行内容。

- 要点一
- 要点二
- 要点三

## 章节 03

第 3 章正文，多行内容。

- 要点一
- 要点二
- 要点三

## 章节 04

第 4 章正文，多行内容。

- 要点一
- 要点二
- 要点三

## 章节 05

第 5 章正文，多行内容。

- 要点一
- 要点二
- 要点三

## 章节 06

第 6 章正文，多行内容。

- 要点一
- 要点二
- 要点三

## 章节 07

第 7 章正文，多行内容。

- 要点一
- 要点二
- 要点三

## 章节 08

第 8 章正文，多行内容。

- 要点一
- 要点二
- 要点三

## 章节 09

第 9 章正文，多行内容。

- 要点一
- 要点二
- 要点三

## 章节 10

第 10 章正文，多行内容。

- 要点一
- 要点二
- 要点三

## 章节 11

第 11 章正文，多行内容。

- 要点一
- 要点二
- 要点三

## 章节 12

第 12 章正文，多行内容。

- 要点一
- 要点二
- 要点三

## 章节 13

第 13 章正文，多行内容。

- 要点一
- 要点二
- 要点三

## 章节 14

第 14 章正文，多行内容。

- 要点一
- 要点二
- 要点三

## 章节 15

第 15 章正文，多行内容。

- 要点一
- 要点二
- 要点三

## 章节 16

第 16 章正文，多行内容。

- 要点一
- 要点二
- 要点三

## 章节 17

第 17 章正文，多行内容。

- 要点一
- 要点二
- 要点三

## 章节 18

第 18 章正文，多行内容。

- 要点一
- 要点二
- 要点三

## 章节 19

第 19 章正文，多行内容。

- 要点一
- 要点二
- 要点三

## 章节 20

第 20 章正文，多行内容。

- 要点一
- 要点二
- 要点三

## 章节 21

第 21 章正文，多行内容。

- 要点一
- 要点二
- 要点三

## 章节 22

第 22 章正文，多行内容。

- 要点一
- 要点二
- 要点三

## 章节 23

第 23 章正文，多行内容。

- 要点一
- 要点二
- 要点三

## 章节 24

第 24 章正文，多行内容。

- 要点一
- 要点二
- 要点三

## 章节 25

第 25 章正文，多行内容。

- 要点一
- 要点二
- 要点三

## 章节 26

第 26 章正文，多行内容。

- 要点一
- 要点二
- 要点三

## 章节 27

第 27 章正文，多行内容。

- 要点一
- 要点二
- 要点三

## 章节 28

第 28 章正文，多行内容。

- 要点一
- 要点二
- 要点三

## 章节 29

第 29 章正文，多行内容。

- 要点一
- 要点二
- 要点三

## 章节 30

第 30 章正文，多行内容。

- 要点一
- 要点二
- 要点三

# 附录
`,
  '探测.md': `# 甲

## 乙

正文内容
`,
  '接口文档/助贷/助贷接口-违规.md': `doctype:接口文档

# 助贷放款申请接口（违规示例）

> ⚠️ 本文件故意违反多条校验规则，用于演示 \`接口文档.rules.ts\` 的违规检出能力。请勿作为真实接口文档使用。

## 基本信息

| 项 | 值 | 备注 |
| --- | --- | :--- |
| 方法 | POST | |
| 路径 | api/loan/apply | 故意缺少前导 \`/\`（违反「路径格式」） |
| 版本号 | 1.0 | 故意非 \`vX.Y.Z\`（违反「版本号格式」） |
| 是否关键接口 | Y | 故意非 是/否（违反「是否关键接口枚举」） |
| 该接口涉及的业务范围 | 助贷放款 | |
| 会调用该接口的系统 | 消金自营系统 | |
| 预计接口并发量 | TPS ≤ 5 | |
| 幂等规则 | [[#applyNo]] | |
| 涉及调用外部接口 | [[后端接口/资金方-XX银行/放款接口]] | |
| 防止重复调用外部接口的机制 | [[数据库/loan/表结构#status]] | |
| 是否涉及分页，分页必须搭配排序 | 否 | |
| 交易状态判断 | [[#status]] | |

## 接口详情

### 助贷放款申请

字段说明：

| 字段 | 类型 | 长度 | 是否高风险字段 | 高风险字段类型 | 数据来源 | 说明 |
| --- | --- | --- | --- | --- | --- | --- |
| applyNo | string | 32 | 是 | 幂等 | [[数据库/loan/表结构#apply_no]] | 放款申请号 |
| amount | bigint | 20 | 是 | 金额 |  | 故意不填数据来源（违反「高风险字段必填数据来源」） |
| status | string | 16 | 是 | 业务状态 | [[数据库/loan/表结构#status]] | 交易状态 |

请求示例：

\`\`\`json
{
  "applyNo": "APL20260806001",
  "amount": 5000000,
  "extraField": "故意多一个未登记字段"
}
\`\`\`

> 上面 \`extraField\` 故意未在字段说明登记（违反「请求/响应示例字段一致性」）。

响应示例：

\`\`\`json
{
  "code": 0,
  "msg": "success",
  "data": {
    "applyNo": "APL20260806001"
  }
}
\`\`\`

> 上面 \`status\` 在字段说明登记但响应示例未出现（违反「请求/响应示例字段一致性」）。

## 变更记录

| 版本 | 日期 | 变更说明 |
| --- | --- | --- |
| 1.0 | 2026-08-06 | 初版 |
`,
  '接口文档/助贷/助贷接口.md': `doctype:接口文档

# 助贷放款申请接口（本系统提供）

## 基本信息

| 项 | 值 | 备注 |
| --- | --- | :--- |
| 方法 | POST | |
| 路径 | /api/loan/apply | |
| 版本号 | v1.0.0 | |
| 是否关键接口 | 是 | 涉及资金交易；包含高风险字段（金额/期次/还款方式/业务状态） |
| 该接口涉及的业务范围 | 助贷放款：合作机构A放款、合作机构B放款 | 穷举所有涉及产品 |
| 会调用该接口的系统 | 消金自营系统、消金业务管理系统 | |
| 预计接口并发量 | TPS ≤ 5 | 2026-08-14 商务XXX与外部约定 TPS 控制在 5 以内 |
| 幂等规则 | [[#applyNo]] | 以申请号 applyNo 作幂等键，重复请求返回原结果 |
| 涉及调用外部接口 | [[后端接口/资金方-XX银行/放款接口]] | 申请受理后调资金方放款接口 |
| 防止重复调用外部接口的机制 | [[数据库/loan/表结构#status]] | 发送外部前更新 loan.status=SENDING（乐观锁），防止重复发起放款 |
| 是否涉及分页，分页必须搭配排序 | 否 | 单笔申请，无分页 |
| 交易状态判断 | [[#status]] | 明确成功=SUCCESS、明确失败=FAIL，其余=PROCESSING 视为处理中 |

## 接口详情

### 助贷放款申请

字段说明：

| 字段 | 类型 | 长度 | 是否高风险字段 | 高风险字段类型 | 数据来源 | 说明 |
| --- | --- | --- | --- | --- | --- | --- |
| applyNo | string | 32 | 是 | 幂等 | [[数据库/loan/loan_apply#apply_no]] | 放款申请号，幂等键 |
| customerId | bigint | 20 | 否 |  | [[数据库/customer/customer_info#id]] | 客户ID |
| amount | bigint | 20 | 是 | 金额 | [[数据库/loan/loan_apply#amount]] | 放款金额（单位：分） |
| term | int | 4 | 是 | 期次 | [[数据库/loan/loan_apply#term]] | 期数 |
| repaymentMethod | string | 16 | 是 | 还款方式 | [[数据库/loan/loan_apply#repayment_method]] | 还款方式（等额本息/等额本金/先息后本） |
| applyDate | date | 10 | 否 |  | [[数据库/loan/loan_apply#apply_date]] | 申请日期 |
| status | string | 16 | 是 | 业务状态 | [[数据库/loan/loan_apply#status]] | 交易状态：PROCESSING/SUCCESS/FAIL |

请求示例：

\`\`\`json
{
  "applyNo": "APL20260806001",
  "customerId": 100200300,
  "amount": 5000000,
  "term": 12,
  "repaymentMethod": "EQUAL_INSTALLMENT",
  "applyDate": "2026-08-06"
}
\`\`\`

响应示例：

\`\`\`json
{
  "code": 0,
  "msg": "success",
  "data": {
    "applyNo": "APL20260806001",
    "status": "PROCESSING"
  }
}
\`\`\`

## 变更记录

| 版本 | 日期 | 变更说明 |
| --- | --- | --- |
| v1.0.0 | 2026-08-06 | 初版 |
`,
  '接口文档/路由/路由接口.md': `# 路由接口（本系统提供）

## 基本信息

| 项 | 值 |
| --- | --- |
| 模块 | 路由 |
| 提供服务 | dispatcher |
| 版本号 | v1.0.0 |

## 接口清单

| 接口名 | 方法 | 路径 | 源文件保存路径 | 状态 |
| --- | --- | --- | --- | --- |
| 路由匹配 | POST | /api/route/match | （待补充：源文件保存路径） | 开发中 |

## 接口详情

### 路由匹配

**请求示例：**

\`\`\`json
{
  "customerId": "C001"
}
\`\`\`

**响应示例：**

\`\`\`json
{
  "orgId": "ORG001"
}
\`\`\`

## 变更记录

（待补充）
`,
  '接口文档/进件/进件接口.md': `# 进件接口（本系统提供）

## 基本信息

| 项 | 值 |
| --- | --- |
| 模块 | 进件 |
| 提供服务 | dispatcher |
| 版本号 | v1.0.0 |

## 接口清单

| 接口名 | 方法 | 路径 | 源文件保存路径 | 状态 |
| --- | --- | --- | --- | --- |
| 客户进件 | POST | /api/entry/submit | （待补充：源文件保存路径） | 开发中 |

## 接口详情

### 客户进件

（待补充：请求/响应示例）

## 变更记录

（待补充）
`,
  '数据库/customer/customer_info.md': `doctype:数据库

# customer_info 客户信息表

## 基本信息

| 项 | 值 | 备注 |
| --- | --- | :--- |
| 表名 | customer_info | |
| 中文名 | 客户信息表 | |
| schema | customer | 客户主档 schema |
| 版本号 | v0.1.0 | |

## 字段说明

| 字段 | 类型 | 约束 | 说明 |
| --- | --- | --- | --- |
| id | bigint | PK 自增 | 主键 |
| name | varchar(64) | 非空 | 客户姓名 |

## 索引

（待补充）

## 变更记录

| 日期 | 变更内容 |
| --- | --- |
| 2026-08-06 | 初版 |
`,
  '数据库/loan/loan_apply-违规.md': `doctype:数据库

# loan_apply 放款申请表

## 基本信息

| 项 | 值 |
| --- | --- |
| 表名 | loan apply |
| 版本号 | 1.0 |

## 字段说明

| 字段 | 约束 | 说明 |
| --- | --- | --- |
| apply no | 非空 | 申请号（字段名含空格） |
| 放款金额 | 非空 | 金额（中文名） |

## 变更记录

| 日期 | 变更内容 |
| --- | --- |
| 2026-08-06 | 初版 |
`,
  '数据库/loan/loan_apply.md': `doctype:数据库

# loan_apply 放款申请表

## 基本信息

| 项 | 值 | 备注 |
| --- | --- | :--- |
| 表名 | loan_apply | |
| 中文名 | 放款申请表 | |
| schema | loan | 放款业务 schema |
| 版本号 | v0.1.0 | 表结构版本 |

## 字段说明

| 字段 | 类型 | 约束 | 说明 |
| --- | --- | --- | --- |
| id | bigint | PK 自增 | 主键 |
| apply_no | varchar(32) | 非空 唯一 | 放款申请号（幂等键） |
| customer_id | bigint | 非空 | 客户ID |
| amount | decimal(18,2) | 非空 | 放款金额（元） |
| term | int | 非空 | 期数 |
| repayment_method | varchar(16) | 非空 | 还款方式：等额本息/等额本金/先息后本 |
| apply_date | date | 非空 | 申请日期 |
| status | varchar(16) | 非空 | 交易状态：PROCESSING/SUCCESS/FAIL |
| create_time | datetime | 非空 | 创建时间 |
| update_time | datetime | 可空 | 更新时间 |

## 索引

| 索引名 | 字段 | 类型 | 说明 |
| --- | --- | --- | --- |
| uk_apply_no | apply_no | 唯一 | 幂等去重 |

## 变更记录

| 日期 | 变更内容 |
| --- | --- |
| 2026-08-06 | 初版：助贷放款申请建表 |
`,
  '数据库/route/表结构.md': `# 表结构：route（schema）

## 基本信息

| 项 | 值 |
| --- | --- |
| schema | route |
| 版本号 | v0.1.0 |

## 表清单

| 表名 | 中文名 | 说明 |
| --- | --- | --- |
| route_rule | 路由规则表 | 路由匹配规则配置 |
| route_record | 路由记录表 | 客户路由匹配历史记录 |
| （待补充） | | |

## route_rule 路由规则表

| 字段 | 类型 | 约束 | 说明 |
| --- | --- | --- | --- |
| id | bigint | PK 自增 | 主键 |
| rule_name | varchar(64) | 非空 | 规则名称 |
| priority | int | 非空 | 优先级 |
| （待补充） | | | |

## 索引

（待补充）

## 变更记录

（待补充）
`,
  '数据库/数据维护/20260806/主题A-历史数据清理.md': `# 数据维护：历史数据清理

## 基本信息

| 项 | 值 |
| --- | --- |
| 维护日期 | 2026-08-06 |
| 主题 | 历史数据清理 |
| 涉及 schema | loan |

## 维护内容

（待补充：清理哪些表、保留策略）

## 执行步骤

1. （待补充）

## 影响范围与风险

（待补充）

## 回滚方案

（待补充）

## 验证方式

（待补充）
`,
  '数据库/数据维护/20260806/主题B-逾期数据修复.md': `# 数据维护：逾期数据修复

## 基本信息

| 项 | 值 |
| --- | --- |
| 维护日期 | 2026-08-06 |
| 主题 | 逾期数据修复 |
| 涉及 schema | loan |

## 维护内容

（待补充）

## 执行步骤

1. （待补充）

## 影响范围与风险

（待补充）

## 回滚方案

（待补充）

## 验证方式

（待补充）
`,
  '数据库/数据维护/20260807/主题C-合作机构数据核对.md': `# 数据维护：合作机构数据核对

## 基本信息

| 项 | 值 |
| --- | --- |
| 维护日期 | 2026-08-07 |
| 主题 | 合作机构数据核对 |
| 涉及 schema | customer / route |

## 维护内容

（待补充）

## 执行步骤

1. （待补充）

## 影响范围与风险

（待补充）

## 回滚方案

（待补充）

## 验证方式

（待补充）
`,
  '数据库/数据维护/20260807/主题D-路由历史数据归档.md': `# 数据维护：路由历史数据归档

## 基本信息

| 项 | 值 |
| --- | --- |
| 维护日期 | 2026-08-07 |
| 主题 | 路由历史数据归档 |
| 涉及 schema | route |

## 维护内容

（待补充）

## 执行步骤

1. （待补充）

## 影响范围与风险

（待补充）

## 回滚方案

（待补充）

## 验证方式

（待补充）
`,
  '数据库字段引用.md': `doctype:demo

# 数据库字段引用演示

本页演示对数据库表结构字段的动态对象引用（M8 objectsFor）。

放款金额取自 [[数据库/loan/loan_apply#amount]]。

申请号取自 [[数据库/loan/loan_apply#apply_no]]。

客户ID取自 [[数据库/customer/customer_info#id]]。
`,
  '流程图/助贷/助贷放款流程.md': `# 助贷放款流程

## 基本信息

| 项    | 值                            |
| ---- | ---------------------------- |
| 图名称  | 助贷放款流程                       |
| 所属模块 | 助贷                           |
| 版本号  | v1.0.0                       |
| 创建人  | （待补充）                        |
| 依赖图  | [[流程图/路由/客户路由匹配流程]]          |
| 关联需求 | [[20260820/项目1-助贷放款流程/需求分析]] |

## 流程图

\`\`\`mermaid
flowchart TD
  A[路由完成] --> B[推送资金方]
  B --> C{放款结果}
  C -->|成功| D[放款成功]
  C -->|失败| E[放款失败处理]
\`\`\`

## 步骤说明

（待补充）

## 变更记录

| 版本     | 日期         | 变更说明 |
| ------ | ---------- | ---- |
| v1.0.0 | 2026-08-20 | 初版   |
`,
  '流程图/路由/客户路由匹配流程.md': `# 客户路由匹配流程

## 基本信息

| 项    | 值                          |
| ---- | -------------------------- |
| 图名称  | 客户路由匹配流程                   |
| 所属模块 | 路由                         |
| 版本号  | v1.0.0                     |
| 创建人  | （待补充）                      |
| 依赖图  | [[流程图/进件/客户进件流程]]          |
| 关联需求 | [[20260806/项目1-路由升级/需求分析]] |

## 流程图

\`\`\`mermaid
flowchart TD
  A[接收意向客户] --> B{路由匹配}
  B -->|命中| C[输出到下游机构]
  B -->|未命中| D[人工处理]
\`\`\`

## 步骤说明

1. 接收上游推送的意向客户
2. （待补充：路由匹配规则说明）

## 变更记录

| 版本     | 日期         | 变更说明 |
| ------ | ---------- | ---- |
| v1.0.0 | 2026-08-06 | 初版   |

`,
  '流程图/进件/客户进件流程.md': `# 客户进件流程

## 基本信息

| 项 | 值 |
| --- | --- |
| 图名称 | 客户进件流程 |
| 所属模块 | 进件 |
| 版本号 | v1.0.0 |
| 创建人 | （待补充） |
| 依赖图 | （待补充） |
| 关联需求 | （待补充） |

## 流程图

\`\`\`mermaid
flowchart TD
  A[客户意向] --> B[信息采集]
  B --> C{资料齐全?}
  C -->|是| D[进件提交]
  C -->|否| E[补充资料]
\`\`\`

## 步骤说明

（待补充）

## 变更记录

| 版本 | 日期 | 变更说明 |
| --- | --- | --- |
| v1.0.0 | 2026-08-06 | 初版 |
`,
  '渐变演示.md': `# 平台指南

## 章节 01

第 1 章正文。

## 章节 02

第 2 章正文。

## 章节 03

第 3 章正文。

## 章节 04

第 4 章正文。

## 章节 05

第 5 章正文。

## 章节 06

第 6 章正文。

## 章节 07

第 7 章正文。

## 章节 08

第 8 章正文。

## 章节 09

第 9 章正文。

## 章节 10

第 10 章正文。

## 章节 11

第 11 章正文。

## 章节 12

第 12 章正文。

## 章节 13

第 13 章正文。

## 章节 14

第 14 章正文。

## 章节 15

第 15 章正文。

## 章节 16

第 16 章正文。

## 章节 17

第 17 章正文。

## 章节 18

第 18 章正文。

## 章节 19

第 19 章正文。

## 章节 20

第 20 章正文。

## 章节 21

第 21 章正文。

## 章节 22

第 22 章正文。

## 章节 23

第 23 章正文。

## 章节 24

第 24 章正文。

## 章节 25

第 25 章正文。

## 章节 26

第 26 章正文。

## 章节 27

第 27 章正文。

## 章节 28

第 28 章正文。

## 章节 29

第 29 章正文。

## 章节 30

第 30 章正文。

## 章节 31

第 31 章正文。

## 章节 32

第 32 章正文。

## 章节 33

第 33 章正文。

## 章节 34

第 34 章正文。

## 章节 35

第 35 章正文。

## 章节 36

第 36 章正文。

## 章节 37

第 37 章正文。

## 章节 38

第 38 章正文。

## 章节 39

第 39 章正文。

## 章节 40

第 40 章正文。

# 附录
`,
  '点击测试.md': `# 短标题

## 子节

正文
`,
  '第二个.md': `# 第二个文件

## 子节

正文
`,
  '自适应测试.md': `# 一个非常非常非常非常非常非常非常非常非常长的标题用来测试自适应宽度上限是否生效的样例

## 短的

正文
`,
  '迭代/20260806/项目1-路由升级/设计文档.md': `# 设计文档：路由升级

> 迭代窗口：20260806 · 项目：项目1-路由升级

## 概述

（待补充：本次迭代的设计目标与范围）

## 架构图

\`\`\`mermaid
flowchart LR
  A[上游] --> B[消金业务合作平台]
  B --> C[下游机构]
\`\`\`

## 模块设计

（待补充）

## 数据库设计

引用表结构：[[数据库/route/表结构]]

## 需求引用

- [[20260806/项目1-路由升级/需求分析#NE-001]]

## 版本

v0.1.0
`,
  '迭代/20260806/项目1-路由升级/需求分析.md': `# 需求分析：路由升级

> 迭代窗口：20260806 · 项目：项目1-路由升级

## 背景与目标

（待补充：路由升级的业务背景、要解决的问题、目标）

## 用户角色

| 角色 | 说明 |
| --- | --- |
| （待补充） | |

## 功能需求

| 编号 | 需求描述 | 优先级 | 验收标准 |
| --- | --- | --- | --- |
| NE-001 | 路由规则支持按机构优先级 | 高 | （待补充） |
| NE-002 | （待补充） | 中 | |

## 非功能需求

（待补充）

## 版本

v0.1.0
`,
  '迭代/20260806/项目2-增信机构接入/设计文档.md': `# 设计文档：增信机构接入

> 迭代窗口：20260806 · 项目：项目2-增信机构接入

## 概述

（待补充）

## 架构图

（待补充）

## 模块设计

（待补充）

## 数据库设计

引用表结构：[[数据库/loan/表结构]]

## 需求引用

- [[20260806/项目2-增信机构接入/需求分析#NE-001]]

## 版本

v0.1.0
`,
  '迭代/20260806/项目2-增信机构接入/需求分析.md': `# 需求分析：增信机构接入

> 迭代窗口：20260806 · 项目：项目2-增信机构接入

## 背景与目标

（待补充：新增增信机构的背景、目标）

## 用户角色

| 角色 | 说明 |
| --- | --- |
| （待补充） | |

## 功能需求

| 编号 | 需求描述 | 优先级 | 验收标准 |
| --- | --- | --- | --- |
| NE-001 | 对接增信机构-XX担保的增信申请接口 | 高 | （待补充） |
| NE-002 | （待补充） | 中 | |

## 非功能需求

（待补充）

## 版本

v0.1.0
`,
  '迭代/20260820/项目1-助贷放款流程/设计文档.md': `# 设计文档：助贷放款流程

> 迭代窗口：20260820 · 项目：项目1-助贷放款流程

## 概述

（待补充）

## 架构图

（待补充）

## 模块设计

（待补充）

## 数据库设计

引用表结构：[[数据库/loan/表结构]]

## 需求引用

- [[20260820/项目1-助贷放款流程/需求分析#NE-001]]

## 版本

v0.1.0
`,
  '迭代/20260820/项目1-助贷放款流程/需求分析.md': `# 需求分析：助贷放款流程

> 迭代窗口：20260820 · 项目：项目1-助贷放款流程

## 背景与目标

（待补充）

## 用户角色

| 角色 | 说明 |
| --- | --- |
| （待补充） | |

## 功能需求

| 编号 | 需求描述 | 优先级 | 验收标准 |
| --- | --- | --- | --- |
| NE-001 | 助贷放款状态流转 | 高 | （待补充） |
| NE-002 | （待补充） | 中 | |

## 非功能需求

（待补充）

## 版本

v0.1.0
`,
  '透明大纲演示.md': `# 消金业务合作平台 · 指南

## 章节 01

这是第 1 章正文。

## 章节 02

这是第 2 章正文。

## 章节 03

这是第 3 章正文。

## 章节 04

这是第 4 章正文。

## 章节 05

这是第 5 章正文。

## 章节 06

这是第 6 章正文。

## 章节 07

这是第 7 章正文。

## 章节 08

这是第 8 章正文。

## 章节 09

这是第 9 章正文。

## 章节 10

这是第 10 章正文。

## 章节 11

这是第 11 章正文。

## 章节 12

这是第 12 章正文。

## 章节 13

这是第 13 章正文。

## 章节 14

这是第 14 章正文。

## 章节 15

这是第 15 章正文。

## 章节 16

这是第 16 章正文。

## 章节 17

这是第 17 章正文。

## 章节 18

这是第 18 章正文。

## 章节 19

这是第 19 章正文。

## 章节 20

这是第 20 章正文。

## 章节 21

这是第 21 章正文。

## 章节 22

这是第 22 章正文。

## 章节 23

这是第 23 章正文。

## 章节 24

这是第 24 章正文。

## 章节 25

这是第 25 章正文。

## 章节 26

这是第 26 章正文。

## 章节 27

这是第 27 章正文。

## 章节 28

这是第 28 章正文。

## 章节 29

这是第 29 章正文。

## 章节 30

这是第 30 章正文。

## 章节 31

这是第 31 章正文。

## 章节 32

这是第 32 章正文。

## 章节 33

这是第 33 章正文。

## 章节 34

这是第 34 章正文。

## 章节 35

这是第 35 章正文。

# 附录
`,
  '配置/apollo/actuator/参数.md': `# Apollo 参数：actuator

## 基本信息

| 项 | 值 |
| --- | --- |
| 应用 | actuator |
| 环境 | dev / test / prod |
| 版本号 | v1.0.0 |

## 参数清单

| Key | 默认值 | 环境 | 说明 | 负责人 |
| --- | --- | --- | --- | --- |
| management.endpoint.health.show-details | always | 全部 | 健康检查明细 | （待补充） |
| （待补充） | | | | |

## 变更记录

（待补充）
`,
  '配置/apollo/dispatcher/参数.md': `# Apollo 参数：dispatcher

## 基本信息

| 项 | 值 |
| --- | --- |
| 应用 | dispatcher |
| 环境 | dev / test / prod |
| 版本号 | v1.0.0 |

## 参数清单

| Key | 默认值 | 环境 | 说明 | 负责人 |
| --- | --- | --- | --- | --- |
| route.match.timeout | 3000 | 全部 | 路由匹配超时(ms) | （待补充） |
| （待补充） | | | | |

## 变更记录

（待补充）
`,
  '配置/apollo/xxljob/参数.md': `# Apollo 参数：xxljob

## 基本信息

| 项 | 值 |
| --- | --- |
| 应用 | xxljob |
| 环境 | dev / test / prod |
| 版本号 | v1.0.0 |

## 参数清单

| Key | 默认值 | 环境 | 说明 | 负责人 |
| --- | --- | --- | --- | --- |
| xxl.job.admin.addresses | http://xxljob:8080/xxl-job-admin | 全部 | 调度中心地址 | （待补充） |
| （待补充） | | | | |

## 变更记录

（待补充）
`,
  '配置/nginx/反向代理.md': `# Nginx 反向代理配置

## 基本信息

| 项 | 值 |
| --- | --- |
| 环境 | prod |
| 版本号 | v1.0.0 |

## 配置内容

（待补充：server 块、upstream、SSL）

## 变更记录

| 版本 | 日期 | 变更说明 |
| --- | --- | --- |
| v1.0.0 | 2026-08-06 | 初版 |
`,
  '错误探测.md': `# 甲

## 乙

正文
`,
  '长文测试.md': `# 平台指南

## 章节 01

第 1 章正文。

## 章节 02

第 2 章正文。

## 章节 03

第 3 章正文。

## 章节 04

第 4 章正文。

## 章节 05

第 5 章正文。

## 章节 06

第 6 章正文。

## 章节 07

第 7 章正文。

## 章节 08

第 8 章正文。

## 章节 09

第 9 章正文。

## 章节 10

第 10 章正文。

## 章节 11

第 11 章正文。

## 章节 12

第 12 章正文。

## 章节 13

第 13 章正文。

## 章节 14

第 14 章正文。

## 章节 15

第 15 章正文。

## 章节 16

第 16 章正文。

## 章节 17

第 17 章正文。

## 章节 18

第 18 章正文。

## 章节 19

第 19 章正文。

## 章节 20

第 20 章正文。

## 章节 21

第 21 章正文。

## 章节 22

第 22 章正文。

## 章节 23

第 23 章正文。

## 章节 24

第 24 章正文。

## 章节 25

第 25 章正文。

## 章节 26

第 26 章正文。

## 章节 27

第 27 章正文。

## 章节 28

第 28 章正文。

## 章节 29

第 29 章正文。

## 章节 30

第 30 章正文。

## 章节 31

第 31 章正文。

## 章节 32

第 32 章正文。

## 章节 33

第 33 章正文。

## 章节 34

第 34 章正文。

## 章节 35

第 35 章正文。

## 章节 36

第 36 章正文。

## 章节 37

第 37 章正文。

## 章节 38

第 38 章正文。

## 章节 39

第 39 章正文。

## 章节 40

第 40 章正文。

## 章节 41

第 41 章正文。

## 章节 42

第 42 章正文。

## 章节 43

第 43 章正文。

## 章节 44

第 44 章正文。

## 章节 45

第 45 章正文。

## 章节 46

第 46 章正文。

## 章节 47

第 47 章正文。

## 章节 48

第 48 章正文。

## 章节 49

第 49 章正文。

## 章节 50

第 50 章正文。

## 章节 51

第 51 章正文。

## 章节 52

第 52 章正文。

## 章节 53

第 53 章正文。

## 章节 54

第 54 章正文。

## 章节 55

第 55 章正文。

## 章节 56

第 56 章正文。

## 章节 57

第 57 章正文。

## 章节 58

第 58 章正文。

## 章节 59

第 59 章正文。

## 章节 60

第 60 章正文。

# 附录
`,
  '验收场景/README.GitDiff验收清单.md': `# Git Diff 渲染验收清单

> 验收环境：\`editor-app\` vite dev（默认真实仓库 = 本目录）。打开应用 → 左侧图标列 🔀 Git 面板。

## 一、验收入口一：历史提交对比（场景干净可重复）

Git 面板 → 历史区，展开最新提交 **5c9f942（场景变更 B）**，逐文件点击查看 diff（渲染模式为默认；右上角工具栏可切「文本」）。

### ① 表格单元格局域（01-表格单元格级.md）
- 单元格内容修改：如「驳回」→「拒绝」逐格红/绿标注（非整行）。
- 整行新增/删除：整行 \`{++..++}\` / \`{--..--}\` 标记。
- 三张表格均正常渲染为表格（不是文本段落）。

### ② 表格分隔行格式化（02-表格分隔行格式化.md）
- 分隔行 \`| --- |\` → \`| ------- |\` 长度变化。
- 预期：**表格正常渲染**；分隔行不出现 {++..++}/{--..--} 噪音；**无「修改了表格单元格」批注卡**。
- 这是本次修复的核心回归点（旧版整表退化成文本段落）。

### ③ 词级行内（03-词级行内.md）
- 中文词级：\`路由匹配\`→\`路由决策\`（共同前后缀行内标记）。
- 同一行多个修改点（\`低优先级\`→\`最高优先级\`、\`高优先级\`→\`低优先级\`）：**字符级 LCS 多点标记**，各自独立红/绿标，标记内不出现 \`*\` 等语法符号（无乱码）。
- 英文句子词级、加粗内词级、链接文本/链接地址变化。

### ④ 块级增删（04-块级增删.md）
- 纯新增段（整段绿）、纯删除段、引用块删除。
- 列表项新增 \`- 丙\`：**保留 \`- \` marker**（\`- {++丙++}\`），独立成列表项、不吞入上一行，且**有「新增了此段」批注卡并正确连线**。
- **无共同内容的修改对 → 拆为上下两行**（旧行红、新行绿），不再行内 \`{--旧--}{++新++}\` 拼接（避免 \`> 引用\` 与 \`## 标题\` 两种块语义被拼进同一行粘连）。

### ⑤ mermaid 流程图（05-mermaid流程图.md）
- **二元语义：只有红（删除）与绿（新增）**，无黄色「修改」标注。
- **C 删除＝红框虚线+划线**、**F 新增＝绿**。
- **D 节点标签修改（人工处理→人工复核）＝「删除后新增」**：节点显示绿色（新值）+ 节点下方红划线旧值小字「人工处理」。
- 批注卡：\`流程图：新增 2 个节点、删除 2 个\`（C 删 F 增 + D 改拆成删旧增新）；点击卡 → 连线 + 滚动定位。

### ⑥ mermaid 时序图（06-mermaid时序图.md）
- 消息文本标注二元：**新增绿 / 删除红（划线）**；删除消息**按原时序插回原位**（先删旧线、再增新线，顺序不乱）。
- **participant 增删也标注**：新增参与者（如 \`风控系统\`）绿色、删除红色（删除行加回图）；本次场景含新增 \`participant D as 风控系统\`。
- 精确文本匹配（\`推送客户\` 不会误命中 \`推送客户资料\`）；批注卡 \`新增 N 个消息、删除 N 个\`。

### ⑦ mermaid 状态图（07-mermaid状态图.md）
- 状态节点标注二元：PENDING/FINISHED 绿（新增）、WAIT/LENDING 红（删除），无黄色修改。
- **删除状态的过渡线一并加回并红标**（\`WAIT --> ROUTED\`、\`ROUTED --> LENDING\`），删除状态不孤立。

### ⑧ 嵌入引用与摘要（08-嵌入引用与摘要.md）
- **二元语义**：移除的引用以**缩略红行**展示（\`移除引用：[[path]]\` 1 行，非卡片）+「移除了引用」批注卡；新增的引用为**卡片 + 「新增引用」绿徽标** +「新增了引用」批注卡（**点击该卡连线到卡片本体并滚动**）。
- 不再出现「引用变更」（黄）概念；末尾新增段落独立成行不粘连。
- **嵌入的源文件改动在当前文件可见**：08 引用的 05/06 图在对比范围内有改动 → 卡片出现**「内容有改动」角标 + 内嵌源文件改动摘要**（mermaid 概要「流程图：新增 1 节点、删除 1」等），像直接看 05/06 的 diff 一样，与工作区还是 commit 对比无关（via base 传参）。

### ⑨ 标题与行内/列表（09-标题行内与列表.md）
- 标题修改（\`## 子标题一\`→\`二\`）：词级标（LCS 保留 \`## \` marker，仍是标题元素）。
- 列表项修改+新增：\`- 事项丙\` 独立列表项 + 批注卡连线正确。
- **同值的多个批注卡精确连线**：两处「一→二」分别连到标题与子标题（批注按 del/add 类型 + 文档顺序 used 去重分配锚点）。

### ⑩ 多 hunk 折叠（10-多hunk折叠.md）
- 三处「将改→已经改过」批注卡**分别连到各自修改行**（同值锚点 used 去重分配，不再全指第 1/3 处）。
- 切「文本」模式：同一 hunk 内 4 行相同段折叠为「⋯ 相同 4 行」，点击展开/收起。
- 顶部 \`◀ ▶\` 或 \`F7 / Shift+F7\` 导航改动点，计数 \`n/2\`。

## 二、验收入口二：工作区 vs HEAD（用户现有未提交改动，含 C 场景）

Git 面板 → 工作区树（5 个改动文件），逐个点击：

### README.md
- 表格「目录约定」分隔行格式化 → 表格正常渲染、无噪音、无批注卡（M16 首轮修复）。
- 新增两个嵌入引用卡片：**「新增引用」（绿）** + **「内容有改动」（黄）** 徽标 + 卡片底部**内嵌源文件改动摘要**：
  - 「流程图/助贷/助贷放款流程.md」摘要含 \`◆ 流程图：新增 1 个节点、删除 1 个节点\`（mermaid 概要）+ 表格行级增减。
  - 「助贷放款申请接口.md」摘要含字段表行级增减。
- 标题 \`消金业务合作平台111\`：\`111\` 词级绿标。
- 批注卡仅 2 张合理卡（新增"111"、新增了此段（5 行））。

### 流程图/助贷/助贷放款流程.md
- mermaid：\`E[放款失败处理]\` 删除节点**红框虚线+划线**；\`F[放款失败不处理]\` 新增节点**绿色**。
- 基本信息 / 变更记录表格分隔行格式化 → 表格正常渲染。

### 流程图/路由/客户路由匹配流程.md
- 两处表格分隔行格式化 → 均正常渲染；**无「修改了表格单元格」批注卡、无 diff 标记噪音**（旧版全部退化为文本段落且批注连线错乱）。

### 后端接口/…/助贷放款申请接口.md
- 大表格单元格级+行级变化；响应示例内容修改词级标。

## 三、交互回归

| 动作 | 预期 |
|---|---|
| 渲染 ⇄ 文本 | 双模式切换不丢内容（Ctrl+Shift+R） |
| 分栏 ⇄ 统一 | Ctrl+Shift+U |
| 批注卡点击 | 连线（抽屉左缘→锚点）+ 平滑滚动 + 锚点闪烁 |
| 还原… / ↩ 还原此段 | 危险确认后还原（仅工作区 diff） |
| Esc / ✕ | 退出 diff 回编辑 |

## 四、验收后清理

- 验收 commit：\`5c9f942\`（B）、\`1664d55\`（A）可随时 \`git reset --hard 1664d55\` 或删分支回退；不影响工作区未提交改动与 init 提交。
- 本清单文件为未跟踪文件；不需要时删除即可。
`,
  '验收场景/git-diff/01-表格单元格级.md': `# 表格单元格局域修改

> 场景一：单元格内容修改会逐格标记（{--旧--}{++新++}）；整行新增/删除整行标记。

## 单元格内容修改

| 序号 | 产品 | 资金方 | 状态 |
| --- | --- | --- | --- |
| 1 | 现金贷 | A银行 | 通过 |
| 2 | 分期贷 | B银行 | 拒绝 |
| 3 | 大额贷 | C银行 | 待审 |
| 4 | 经营贷 | D银行 | 新增行 |

## 整行新增

| 序号 | 产品 |
| --- | --- |
| 1 | 现金贷 |
| 2 | 分期贷 |

## 整行删除

| 序号 | 产品 |
| --- | --- |
| 1 | 现金贷 |
| 3 | 大额贷 |
`,
  '验收场景/git-diff/02-表格分隔行格式化.md': `# 表格分隔行格式化

> 场景二：仅分隔行 \`---\` 长度变化（列宽对齐格式化）。预期：表格正常渲染、分隔行不产生 {++..++}/{--..--} 噪音、无批注卡。

| 目录     | 含义        |
| ------- | ---------- |
| 流程     | 当前状态      |
| 数据     | 明细表       |
`,
  '验收场景/git-diff/03-词级行内.md': `# 词级行内修改

> 场景三：中文词级（共同前后缀）、英文句子、加粗/强调内词级、链接文本。

- 中文：本系统负责客户**路由决策**与放款流程。
- 英文：The system routes customers to downstream lenders.
- 强调：请优先处理*最高优先级*任务，其次处理*低优先级*任务。
- 链接：[历史需求文档](../迭代/20260820/项目1-助贷放款流程/需求分析)
`,
  '验收场景/git-diff/04-块级增删.md': `# 块级增删

> 场景四：纯新增段、纯删除段、列表项增删、引用块增删。

## 纯新增占位

这里是一段新增的说明文字，包含**加粗**与普通内容，验证纯新增段落整体标记。

## 纯删除占位

## 列表项

- 甲
- 乙新增
- 丙
- 丁
`,
  '验收场景/git-diff/05-mermaid流程图.md': `# 流程图节点级 diff

> 场景五：flowchart 节点 新增（绿）/ 删除（红划线）/ 修改（黄）三种标注。么111

## 路由决策流程

\`\`\`mermaid
flowchart TD
  A[接收客户] --> B{路由规则}
  B -->|命中| F[输出到合作机构]
  B -->|未命中| D[人工复核]
\`\`\`
`,
  '验收场景/git-diff/06-mermaid时序图.md': `# 时序图消息级 diff

> 场景六：sequenceDiagram 消息 新增 / 修改 / 删除。

## 助贷放款时序

\`\`\`mermaid
sequenceDiagram
  participant A as 客户
  participant B as 路由系统
  participant C as 下游机构
  participant D as 风控系统
  A->>B: 提交贷款申请
  B->>C: 推送客户资料
  B->>D: 发起风控
  C-->>B: 返回受理结果
  B-->>A: 通知客户进度
  D-->>B: 风控通过
\`\`\`
`,
  '验收场景/git-diff/07-mermaid状态图.md': `# 状态图节点级 diff

> 场景七：stateDiagram 状态 新增 / 删除 / 修改。

## 订单生命周期

\`\`\`mermaid
stateDiagram-v2
  state "待处理" as PENDING
  state "已路由" as ROUTED
  state "已完成" as FINISHED
  PENDING --> ROUTED
  ROUTED --> FINISHED
\`\`\`
`,
  '验收场景/git-diff/08-嵌入引用与摘要.md': `# 嵌入引用与摘要

> 场景八：引用行本身的 新增引用（绿）/ 移除引用（红）/ 引用变更（黄）三类徽标。

## 引用改为新文件

![[验收场景/git-diff/05-mermaid流程图]]

## 新增引用

![[验收场景/git-diff/06-mermaid时序图]]

## 一段说明

原引用 01/02 的语句已在本版本被移除或变更。
`,
  '验收场景/git-diff/09-标题行内与列表.md': `# 标题与行内（版本二）

> 场景九：标题整行修改、加粗词级、列表项增改。

## 子标题二

正文**加粗变更**和_emphasis_。

- 事项甲
- 事项乙改
- 事项丙

1. 步骤一
2. 步骤三

> 引用块保持原样。
`,
  '验收场景/git-diff/10-多hunk折叠.md': `# 多 hunk 与折叠

> 场景十：同一 hunk 内被两次修改夹住的长相同段会折叠为「⋯ 相同 N 行」（点击展开）；多 hunk 用 F7 / Shift+F7 导航（n/N 计数）。

## 第一节

这一行保持不动。

AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB

## 第二节

这一行已经改过第一次。
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFF 这一行已经改过第二次。

## 第三节

这一行也保持不动。

NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN

OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO

PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP

QQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ

RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR

这一行已经改过第三次。

## 结尾

末尾段落。
`,
}

export const DEMO_DIRS: string[] = [
  '.template',
  '.template/xxljob',
  '.template/后端接口',
  '.template/接口文档',
  '.template/数据库',
  '.template/流程图',
  '.template/表结构',
  '.template/设计文档',
  '.template/需求分析',
  '.validate',
  'xxljob',
  'xxljob/notify-executor',
  'xxljob/route-executor',
  '后端接口',
  '后端接口/助贷机构-XX助贷',
  '后端接口/助贷机构-XX助贷/助贷接口',
  '后端接口/增信机构-XX担保',
  '后端接口/资金方-XX银行',
  '接口文档',
  '接口文档/助贷',
  '接口文档/路由',
  '接口文档/进件',
  '数据库',
  '数据库/customer',
  '数据库/loan',
  '数据库/route',
  '数据库/数据维护',
  '数据库/数据维护/20260806',
  '数据库/数据维护/20260807',
  '流程图',
  '流程图/助贷',
  '流程图/路由',
  '流程图/进件',
  '迭代',
  '迭代/20260806',
  '迭代/20260806/项目1-路由升级',
  '迭代/20260806/项目2-增信机构接入',
  '迭代/20260820',
  '迭代/20260820/项目1-助贷放款流程',
  '配置',
  '配置/apollo',
  '配置/apollo/actuator',
  '配置/apollo/dispatcher',
  '配置/apollo/xxljob',
  '配置/nginx',
  '验收场景',
  '验收场景/git-diff',
]

/** 全部 demo 文件内容的聚合 hash（校验同步状态用） */
export const DEMO_HASH = '1st2aet'
