import { expect, test } from '@playwright/test'

test('disclosures support keyboard, Escape, outside click and focus exit', async ({ page }) => {
  await page.goto('/')
  const trigger = page.locator('.document-menu > summary')
  await trigger.focus()
  await trigger.press('Enter')
  await expect(page.locator('.document-menu')).toHaveAttribute('open', '')
  await page.keyboard.press('Tab')
  await expect(page.getByTestId('export-format')).toBeFocused()
  await page.keyboard.press('Escape')
  await expect(trigger).toBeFocused()
  await expect(page.locator('.document-menu')).not.toHaveAttribute('open', '')
  await trigger.press('ArrowDown')
  await expect(page.getByTestId('export-format')).toBeFocused()
  await page.getByTestId('workspace-save').click()
  await expect(page.locator('.document-menu')).not.toHaveAttribute('open', '')
  await trigger.click()
  await page.getByTestId('workspace-save').focus()
  await expect(page.locator('.document-menu')).not.toHaveAttribute('open', '')
})

test('settings traps focus, ignores workspace shortcuts, and restores its trigger', async ({ page }) => {
  await page.goto('/')
  const editor = page.locator('.editor-host > .cm-editor').first()
  await editor.evaluate(el => el.setAttribute('data-focus-identity', 'same'))
  const trigger = page.getByTestId('workspace-settings-toggle')
  await trigger.click()
  const close = page.getByTestId('workspace-settings-close')
  await expect(close).toBeFocused()
  await page.keyboard.press('Shift+Tab')
  await expect(page.getByTestId('workspace-settings-panel')).toContainText('Settings')
  expect(await page.evaluate(() => !!document.activeElement?.closest('#workspace-settings-panel'))).toBe(true)
  await page.keyboard.press('Tab')
  await expect(close).toBeFocused()
  await page.keyboard.press('Control+e')
  await expect(page.getByTestId('presentation-mode')).toHaveText('Raw Source')
  await page.keyboard.press('Escape')
  await expect(page.getByTestId('workspace-settings-panel')).toHaveCount(0)
  await expect(trigger).toBeFocused()
  await expect(editor).toHaveAttribute('data-focus-identity', 'same')
  await expect(editor).not.toHaveAttribute('inert', '')
})

test('context Escape returns focus and deletion Escape cancels without losing text', async ({ page }) => {
  await page.addInitScript(() => localStorage.setItem('writeit-v2.workspace-settings', JSON.stringify({ version: 1, settings: { autoSaveDelayMs: null } })))
  await page.goto('/')
  const editor = page.locator('.editor-host > .cm-editor .cm-content').first()
  await editor.click()
  await page.keyboard.press('End')
  await page.keyboard.insertText(' keep this edit')
  const row = page.locator('[data-workspace-path="welcome.md"] .workspace-tree__row')
  await row.click({ button: 'right' })
  await expect(page.getByTestId('workspace-context-copy')).toBeFocused()
  await page.keyboard.press('Escape')
  await expect(page.getByTestId('workspace-context-menu')).toHaveCount(0)
  await expect(row).toBeFocused()
  const remove = page.getByRole('button', { name: 'Delete welcome.md', exact: true })
  await remove.click()
  await expect(page.getByTestId('workspace-delete-dialog')).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(page.getByTestId('workspace-delete-dialog')).toHaveCount(0)
  await expect(remove).toBeFocused()
  await expect(editor).toContainText('keep this edit')
  await expect(page.getByTestId('persistence-status')).toHaveText('未保存')
})
