import { expect, test } from '@playwright/test'

test('workspace context actions support keyboard without restoring removed header entries', async ({ page }) => {
  await page.goto('/')
  await expect(page.locator('.document-menu')).toHaveCount(0)
  await expect(page.getByTestId('workspace-save')).toHaveCount(0)
  await expect(page.getByTestId('workspace-reveal-current')).toHaveCount(0)

  const row = page.locator('[data-workspace-path="welcome.md"] .workspace-tree__row')
  await row.click({ button: 'right' })
  await expect(page.getByTestId('workspace-context-menu')).toBeVisible()
  await expect(page.getByTestId('workspace-context-reveal')).toBeFocused()
  await page.keyboard.press('Tab')
  await expect(page.getByTestId('workspace-context-copy')).toBeFocused()
  await page.keyboard.press('Tab')
  await expect(page.getByTestId('workspace-create').locator('summary')).toBeFocused()
  await page.keyboard.press('ArrowDown')
  await expect(page.getByTestId('workspace-entry-name')).toBeFocused()
  await page.keyboard.press('Escape')
  await expect(page.getByTestId('workspace-create').locator('summary')).toBeFocused()
  await page.keyboard.press('Escape')
  await expect(page.getByTestId('workspace-context-menu')).toHaveCount(0)
  await expect(row).toBeFocused()
})

test('settings traps focus, ignores workspace shortcuts, and restores its trigger', async ({ page }) => {
  await page.goto('/')
  const editor = page.locator('.editor-host > .cm-editor').first()
  await editor.evaluate(el => el.setAttribute('data-focus-identity', 'same'))
  const trigger = page.getByTestId('workspace-settings-toggle')
  await trigger.click()
  const close = page.getByTestId('workspace-settings-close')
  await expect(close).toBeFocused()
  await page.keyboard.press('Shift+Tab')
  const settings = page.getByTestId('workspace-settings-panel')
  await expect(settings).toContainText('设置')
  await expect(settings.getByRole('tab', { name: '工作区' })).toBeVisible()
  await expect(settings.getByRole('tab', { name: '快捷键' })).toBeVisible()
  await settings.getByRole('tab', { name: '快捷键' }).click()
  await expect(settings.getByTestId('shortcut-settings')).toBeVisible()
  expect(await page.evaluate(() => !!document.activeElement?.closest('#workspace-settings-panel'))).toBe(true)
  await close.focus()
  await page.keyboard.press('Shift+Tab')
  await page.keyboard.press('Tab')
  await expect(close).toBeFocused()
  await page.keyboard.press('Control+e')
  await expect(page.getByTestId('presentation-mode')).toHaveCount(0)
  await page.keyboard.press('Escape')
  await expect(page.getByTestId('workspace-settings-panel')).toHaveCount(0)
  await expect(trigger).toBeFocused()
  await expect(editor).toHaveAttribute('data-focus-identity', 'same')
  await expect(editor).not.toHaveAttribute('inert', '')
})

test('context Escape returns focus and deletion Escape cancels without losing text', async ({ page }) => {
  await page.addInitScript(() => localStorage.setItem('writeit-v2.workspace-settings', JSON.stringify({ version: 1, settings: { autoSaveDelayMs: null } })))
  await page.goto('/')
  const editor = page.locator('.editor-host > .cm-editor .cm-content').first()
  await editor.click()
  await page.keyboard.press('End')
  await page.keyboard.insertText(' keep this edit')
  const row = page.locator('[data-workspace-path="welcome.md"] .workspace-tree__row')
  await row.click({ button: 'right' })
  await expect(page.getByTestId('workspace-context-reveal')).toBeFocused()
  await page.keyboard.press('Escape')
  await expect(page.getByTestId('workspace-context-menu')).toHaveCount(0)
  await expect(row).toBeFocused()
  const remove = page.getByRole('button', { name: 'Delete welcome.md', exact: true })
  await remove.click()
  await expect(page.getByTestId('workspace-delete-dialog')).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(page.getByTestId('workspace-delete-dialog')).toHaveCount(0)
  await expect(remove).toBeFocused()
  await expect(editor).toContainText('keep this edit')
  await expect(page.getByTestId('persistence-status')).toHaveText('未保存')
})
