import { expect, test } from '@playwright/test'

test('editor fills the workspace and optional panels preserve the editor', async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 900 })
  await page.goto('/')
  const editor = page.locator('.editor-host > .cm-editor').first()
  await expect(editor).toBeVisible()
  await expect(page.locator('.preview-card')).toBeHidden()
  const bounds = await editor.boundingBox()
  expect(bounds!.width).toBeGreaterThan(1000)
  expect(bounds!.height).toBeGreaterThan(650)
  await editor.evaluate(el => el.setAttribute('data-shell-identity', 'retained'))
  await page.getByRole('button', { name: '大纲', exact: true }).click()
  await page.getByRole('button', { name: '批注', exact: true }).click()
  await expect(page.getByTestId('workspace-outline')).toBeVisible()
  await expect(page.getByTestId('annotation-drawer')).toBeVisible()
  await page.getByTestId('workspace-tool-search').click()
  await expect(editor).toHaveAttribute('data-shell-identity', 'retained')
  await page.getByRole('button', { name: '大纲', exact: true }).click()
  await page.getByTestId('annotation-drawer-close').click()
  await page.getByTestId('workspace-tool-files').click()
  await page.locator('.document-menu > summary').click()
  await page.getByRole('button', { name: '对照预览' }).click()
  await expect(page.locator('.preview-card')).toBeVisible()
  await page.getByRole('button', { name: '对照预览' }).click()
  await page.locator('.document-menu > summary').click()
  await page.getByTestId('presentation-toggle').click()
  await expect(editor).toHaveAttribute('data-shell-identity', 'retained')
  await expect(page.getByTestId('presentation-mode')).toHaveText('Live Preview')
  await page.setViewportSize({ width: 900, height: 650 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await expect(page.getByTestId('document-stats')).toBeInViewport()
})
