// sync-demo.mjs —— 消金业务合作平台内容库 → src/fs/mock-samples.generated.ts
// 内容库（独立 git 仓库 `/Users/huyongsheng/project/消金业务合作平台`）是唯一源：mock 浏览器演示数据跟随内容库。predev/prebuild 自动执行。
// 用法：node scripts/sync-demo.mjs          （生成）
//       node scripts/sync-demo.mjs --check  （校验：有差异则 exit 1，供 CI）
// 注意：CI/其他机器没有本地内容库目录时自动跳过（改用已入库的 mock-samples.generated.ts）。
import { existsSync, readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs'
import { join, relative, sep } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = fileURLToPath(new URL('.', import.meta.url))
const ROOT = '/Users/huyongsheng/project/消金业务合作平台'
const OUT = join(__dirname, '../src/fs/mock-samples.generated.ts')

// 本地内容库不存在（CI、其他机器）：直接使用已入库的生成文件，跳过同步
if (!existsSync(ROOT)) {
  console.log(`[sync-demo] 跳过：本地内容库 ${ROOT} 不存在（CI/其他机器）——使用已入库的 mock-samples.generated.ts`)
  process.exit(0)
}

const esc = (s) => s.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${')

/** 递归收集 文件 + 目录（排除 .gitkeep，目录含空目录） */
function walk(dir) {
  const files = []
  const dirs = []
  for (const entry of readdirSync(dir)) {
    const p = join(dir, entry)
    const rel = relative(ROOT, p).split(sep).join('/')
    if (statSync(p).isDirectory()) {
      dirs.push(rel)
      const sub = walk(p)
      files.push(...sub.files)
      dirs.push(...sub.dirs)
    } else if (entry !== '.gitkeep') {
      files.push(rel)
    }
  }
  return { files, dirs }
}

function hash(s) {
  let x = 0
  for (let i = 0; i < s.length; i++) x = (Math.imul(x, 31) + s.charCodeAt(i)) | 0
  return (x >>> 0).toString(36)
}

const { files, dirs } = walk(ROOT)
files.sort()
dirs.sort()
const entries = files.map((p) => `  '${p}': \`${esc(readFileSync(join(ROOT, p), 'utf8'))}\`,`)
const all = files.map((p) => readFileSync(join(ROOT, p), 'utf8')).join('\n')

const out =
  `// AUTO-GENERATED by scripts/sync-demo.mjs —— 不要手改；demo/ 变更后运行 npm run sync:demo（predev/prebuild 自动执行）\n` +
  `// demo 目录是唯一源，mock 浏览器演示数据与其同步。\n` +
  `export const DEMO_FILES: Record<string, string> = {\n${entries.join('\n')}\n}\n\n` +
  `export const DEMO_DIRS: string[] = [\n${dirs.map((d) => `  '${d}',`).join('\n')}\n]\n\n` +
  `/** 全部 demo 文件内容的聚合 hash（校验同步状态用） */\nexport const DEMO_HASH = '${hash(all)}'\n`

if (process.argv.includes('--check')) {
  let cur = ''
  try { cur = readFileSync(OUT, 'utf8') } catch { /* 不存在视为全差异 */ }
  if (cur === out) {
    console.log('[sync-demo] OK：demo 与 mock-samples.generated.ts 一致')
    process.exit(0)
  }
  console.log('[sync-demo] 差异：demo/ 与 mock-samples.generated.ts 不一致，运行 npm run sync:demo 同步')
  console.log(`  demo 文件数: ${files.length}, 目录数: ${dirs.length}, hash: ${hash(all)}`)
  process.exit(1)
}

writeFileSync(OUT, out)
console.log(`[sync-demo] 已生成 mock-samples.generated.ts：${files.length} 文件 / ${dirs.length} 目录 / hash ${hash(all)}`)
